# Generated from google/api/annotations.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.6.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Final, TYPE_CHECKING

from protobuf import Extension
from protobuf._codegen import file_desc
from protobuf.wkt.google.protobuf import descriptor_pb
from protobuf.wkt.google.protobuf.descriptor_pb import MethodOptions

from . import http_pb
from .http_pb import HttpRule

if TYPE_CHECKING:
    from protobuf import DescFile


ext_http: Final[Extension[MethodOptions, HttpRule]] = Extension()
"""
See `HttpRule`.

```proto
extend google.protobuf.MethodOptions { optional google.api.HttpRule http = 72295728 [json_name = "[google.api.http]"] }
```
"""


_DESC = file_desc(
    b'\n\x1cgoogle/api/annotations.proto\x12\ngoogle.api\x1a\x15google/api/http.proto\x1a google/protobuf/descriptor.proto:K\n\x04http\x18\xb0\xca\xbc" \x01(\x0b2\x14.google.api.HttpRule\x12\x1e.google.protobuf.MethodOptionsR\x04httpBn\n\x0ecom.google.apiB\x10AnnotationsProtoP\x01ZAgoogle.golang.org/genproto/googleapis/api/annotations;annotations\xa2\x02\x04GAPIb\x06proto3',
    [
        http_pb.desc(),
        descriptor_pb.desc(),
    ],
    {
        "http": ext_http,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `google/api/annotations.proto`."""
    return _DESC
