"""Alembic environment.

The engine is the application's own, from ``app.db``, so a migration cannot be
pointed at a database the code does not use. That engine is async, which Alembic
is not, so the whole migration runs inside ``connection.run_sync``.
"""

from __future__ import annotations

import asyncio

from alembic import context
from app.db import Base, engine

# Importing the models is what registers them on the metadata; without it
# autogenerate would see an empty schema and propose dropping everything.
from app import models  # noqa: F401  isort:skip

config = context.config
target_metadata = Base.metadata


def _configure(connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Postgres and SQLite disagree about how a type is spelled, and without
        # this an autogenerated revision is full of no-op type changes.
        compare_type=True,
        render_as_batch=connection.dialect.name == "sqlite",
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it, for review before a release."""
    context.configure(
        url=str(engine.url),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    async with engine.connect() as connection:
        await connection.run_sync(lambda sync_conn: _run(sync_conn))
    await engine.dispose()


def _run(sync_connection) -> None:
    _configure(sync_connection)
    with context.begin_transaction():
        context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
