# Generated from lessons/v2/access_request.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import access_request_pb
from .access_request_pb import ApproveAccessRequestRequest, ApproveAccessRequestResponse, DeclineAccessRequestRequest, DeclineAccessRequestResponse, ListAccessRequestsRequest, ListAccessRequestsResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class AccessRequestService(Protocol):
    async def list_access_requests(self, request: ListAccessRequestsRequest, ctx: RequestContext[ListAccessRequestsRequest, ListAccessRequestsResponse], /) -> ListAccessRequestsResponse:
        """
        Everybody waiting for a role, oldest first.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def approve_access_request(self, request: ApproveAccessRequestRequest, ctx: RequestContext[ApproveAccessRequestRequest, ApproveAccessRequestResponse], /) -> ApproveAccessRequestResponse:
        """
        Grants the role through the same rules as «👥 Доступ» in the bot, and
        tells the requester in Telegram, where they asked. ROLE_GRANT_REFUSED
        when the ladder does not allow it. RESOURCE_NOT_FOUND for a request
        already answered, so two admins cannot grant twice.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def decline_access_request(self, request: DeclineAccessRequestRequest, ctx: RequestContext[DeclineAccessRequestRequest, DeclineAccessRequestResponse], /) -> DeclineAccessRequestResponse:
        """
        Says no, and tells the requester; they keep whatever role they had.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in access_request_pb.desc().services if s.type_name == 'lessons.v2.AccessRequestService')

class AccessRequestServiceASGIApplication(ConnectASGIApplication[AccessRequestService]):
    def __init__(
        self,
        service: AccessRequestService | AsyncGenerator[AccessRequestService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/lessons.v2.AccessRequestService/ListAccessRequests": Endpoint.unary(
                    method=MethodInfo(
                        name="ListAccessRequests",
                        service_name="lessons.v2.AccessRequestService",
                        input=ListAccessRequestsRequest,
                        output=ListAccessRequestsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_access_requests,
                ),
                "/lessons.v2.AccessRequestService/ApproveAccessRequest": Endpoint.unary(
                    method=MethodInfo(
                        name="ApproveAccessRequest",
                        service_name="lessons.v2.AccessRequestService",
                        input=ApproveAccessRequestRequest,
                        output=ApproveAccessRequestResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.approve_access_request,
                ),
                "/lessons.v2.AccessRequestService/DeclineAccessRequest": Endpoint.unary(
                    method=MethodInfo(
                        name="DeclineAccessRequest",
                        service_name="lessons.v2.AccessRequestService",
                        input=DeclineAccessRequestRequest,
                        output=DeclineAccessRequestResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.decline_access_request,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.AccessRequestService"


class AccessRequestServiceClient(ConnectClient):
    async def list_access_requests(
        self,
        request: ListAccessRequestsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListAccessRequestsResponse:
        """
        Everybody waiting for a role, oldest first.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAccessRequests",
                service_name="lessons.v2.AccessRequestService",
                input=ListAccessRequestsRequest,
                output=ListAccessRequestsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def approve_access_request(
        self,
        request: ApproveAccessRequestRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ApproveAccessRequestResponse:
        """
        Grants the role through the same rules as «👥 Доступ» in the bot, and
        tells the requester in Telegram, where they asked. ROLE_GRANT_REFUSED
        when the ladder does not allow it. RESOURCE_NOT_FOUND for a request
        already answered, so two admins cannot grant twice.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ApproveAccessRequest",
                service_name="lessons.v2.AccessRequestService",
                input=ApproveAccessRequestRequest,
                output=ApproveAccessRequestResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def decline_access_request(
        self,
        request: DeclineAccessRequestRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeclineAccessRequestResponse:
        """
        Says no, and tells the requester; they keep whatever role they had.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeclineAccessRequest",
                service_name="lessons.v2.AccessRequestService",
                input=DeclineAccessRequestRequest,
                output=DeclineAccessRequestResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class AccessRequestServiceSync(Protocol):
    def list_access_requests(self, request: ListAccessRequestsRequest, ctx: RequestContext[ListAccessRequestsRequest, ListAccessRequestsResponse], /) -> ListAccessRequestsResponse:
        """
        Everybody waiting for a role, oldest first.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def approve_access_request(self, request: ApproveAccessRequestRequest, ctx: RequestContext[ApproveAccessRequestRequest, ApproveAccessRequestResponse], /) -> ApproveAccessRequestResponse:
        """
        Grants the role through the same rules as «👥 Доступ» in the bot, and
        tells the requester in Telegram, where they asked. ROLE_GRANT_REFUSED
        when the ladder does not allow it. RESOURCE_NOT_FOUND for a request
        already answered, so two admins cannot grant twice.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def decline_access_request(self, request: DeclineAccessRequestRequest, ctx: RequestContext[DeclineAccessRequestRequest, DeclineAccessRequestResponse], /) -> DeclineAccessRequestResponse:
        """
        Says no, and tells the requester; they keep whatever role they had.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in access_request_pb.desc().services if s.type_name == 'lessons.v2.AccessRequestService')

class AccessRequestServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: AccessRequestServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/lessons.v2.AccessRequestService/ListAccessRequests": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListAccessRequests",
                        service_name="lessons.v2.AccessRequestService",
                        input=ListAccessRequestsRequest,
                        output=ListAccessRequestsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_access_requests,
                ),
                "/lessons.v2.AccessRequestService/ApproveAccessRequest": EndpointSync.unary(
                    method=MethodInfo(
                        name="ApproveAccessRequest",
                        service_name="lessons.v2.AccessRequestService",
                        input=ApproveAccessRequestRequest,
                        output=ApproveAccessRequestResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.approve_access_request,
                ),
                "/lessons.v2.AccessRequestService/DeclineAccessRequest": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeclineAccessRequest",
                        service_name="lessons.v2.AccessRequestService",
                        input=DeclineAccessRequestRequest,
                        output=DeclineAccessRequestResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.decline_access_request,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.AccessRequestService"


class AccessRequestServiceClientSync(ConnectClientSync):
    def list_access_requests(
        self,
        request: ListAccessRequestsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListAccessRequestsResponse:
        """
        Everybody waiting for a role, oldest first.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAccessRequests",
                service_name="lessons.v2.AccessRequestService",
                input=ListAccessRequestsRequest,
                output=ListAccessRequestsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def approve_access_request(
        self,
        request: ApproveAccessRequestRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ApproveAccessRequestResponse:
        """
        Grants the role through the same rules as «👥 Доступ» in the bot, and
        tells the requester in Telegram, where they asked. ROLE_GRANT_REFUSED
        when the ladder does not allow it. RESOURCE_NOT_FOUND for a request
        already answered, so two admins cannot grant twice.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ApproveAccessRequest",
                service_name="lessons.v2.AccessRequestService",
                input=ApproveAccessRequestRequest,
                output=ApproveAccessRequestResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def decline_access_request(
        self,
        request: DeclineAccessRequestRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeclineAccessRequestResponse:
        """
        Says no, and tells the requester; they keep whatever role they had.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeclineAccessRequest",
                service_name="lessons.v2.AccessRequestService",
                input=DeclineAccessRequestRequest,
                output=DeclineAccessRequestResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
