# Generated from lessons/v2/audit.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import audit_pb
from .audit_pb import ListAuditEntriesRequest, ListAuditEntriesResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class AuditService(Protocol):
    async def list_audit_entries(self, request: ListAuditEntriesRequest, ctx: RequestContext[ListAuditEntriesRequest, ListAuditEntriesResponse], /) -> ListAuditEntriesResponse:
        """
        Newest first, `page_size` lines at a time: 30 when unset, and a larger
        one than 100 is read as 100 (AIP-158). `next_page_token` is empty on the
        last page. There is no total, because the log only grows and counting it
        would scan it on every page turn. A page token is opaque: send back a
        `next_page_token` unchanged. A line written between two page turns moves
        nothing on the next page. A token this list did not hand out, or a
        negative `page_size`, is VALIDATION_FAILED on that field.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in audit_pb.desc().services if s.type_name == 'lessons.v2.AuditService')

class AuditServiceASGIApplication(ConnectASGIApplication[AuditService]):
    def __init__(
        self,
        service: AuditService | AsyncGenerator[AuditService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/lessons.v2.AuditService/ListAuditEntries": Endpoint.unary(
                    method=MethodInfo(
                        name="ListAuditEntries",
                        service_name="lessons.v2.AuditService",
                        input=ListAuditEntriesRequest,
                        output=ListAuditEntriesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_audit_entries,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.AuditService"


class AuditServiceClient(ConnectClient):
    async def list_audit_entries(
        self,
        request: ListAuditEntriesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListAuditEntriesResponse:
        """
        Newest first, `page_size` lines at a time: 30 when unset, and a larger
        one than 100 is read as 100 (AIP-158). `next_page_token` is empty on the
        last page. There is no total, because the log only grows and counting it
        would scan it on every page turn. A page token is opaque: send back a
        `next_page_token` unchanged. A line written between two page turns moves
        nothing on the next page. A token this list did not hand out, or a
        negative `page_size`, is VALIDATION_FAILED on that field.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAuditEntries",
                service_name="lessons.v2.AuditService",
                input=ListAuditEntriesRequest,
                output=ListAuditEntriesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

class AuditServiceSync(Protocol):
    def list_audit_entries(self, request: ListAuditEntriesRequest, ctx: RequestContext[ListAuditEntriesRequest, ListAuditEntriesResponse], /) -> ListAuditEntriesResponse:
        """
        Newest first, `page_size` lines at a time: 30 when unset, and a larger
        one than 100 is read as 100 (AIP-158). `next_page_token` is empty on the
        last page. There is no total, because the log only grows and counting it
        would scan it on every page turn. A page token is opaque: send back a
        `next_page_token` unchanged. A line written between two page turns moves
        nothing on the next page. A token this list did not hand out, or a
        negative `page_size`, is VALIDATION_FAILED on that field.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in audit_pb.desc().services if s.type_name == 'lessons.v2.AuditService')

class AuditServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: AuditServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/lessons.v2.AuditService/ListAuditEntries": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListAuditEntries",
                        service_name="lessons.v2.AuditService",
                        input=ListAuditEntriesRequest,
                        output=ListAuditEntriesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_audit_entries,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.AuditService"


class AuditServiceClientSync(ConnectClientSync):
    def list_audit_entries(
        self,
        request: ListAuditEntriesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListAuditEntriesResponse:
        """
        Newest first, `page_size` lines at a time: 30 when unset, and a larger
        one than 100 is read as 100 (AIP-158). `next_page_token` is empty on the
        last page. There is no total, because the log only grows and counting it
        would scan it on every page turn. A page token is opaque: send back a
        `next_page_token` unchanged. A line written between two page turns moves
        nothing on the next page. A token this list did not hand out, or a
        negative `page_size`, is VALIDATION_FAILED on that field.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAuditEntries",
                service_name="lessons.v2.AuditService",
                input=ListAuditEntriesRequest,
                output=ListAuditEntriesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
