# Generated from lessons/v2/bell.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import bell_pb
from .bell_pb import CreateBellScheduleRequest, CreateBellScheduleResponse, DeleteBellScheduleRequest, DeleteBellScheduleResponse, GetBellScheduleRequest, GetBellScheduleResponse, ListBellSchedulesRequest, ListBellSchedulesResponse, UpdateBellScheduleRequest, UpdateBellScheduleResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class BellService(Protocol):
    async def list_bell_schedules(self, request: ListBellSchedulesRequest, ctx: RequestContext[ListBellSchedulesRequest, ListBellSchedulesResponse], /) -> ListBellSchedulesResponse:
        """
        Every schedule the class keeps («Обычное», «Сокращённое», «Суббота»),
        with the default marked.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_bell_schedule(self, request: GetBellScheduleRequest, ctx: RequestContext[GetBellScheduleRequest, GetBellScheduleResponse], /) -> GetBellScheduleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def create_bell_schedule(self, request: CreateBellScheduleRequest, ctx: RequestContext[CreateBellScheduleRequest, CreateBellScheduleResponse], /) -> CreateBellScheduleResponse:
        """
        A new named schedule, with its rows if they come with it. It does not
        become the default: a shortened schedule exists to be pointed at by
        particular days. REST answers 201.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def update_bell_schedule(self, request: UpdateBellScheduleRequest, ctx: RequestContext[UpdateBellScheduleRequest, UpdateBellScheduleResponse], /) -> UpdateBellScheduleResponse:
        """
        `update_mask` takes name, is_default and periods. Periods are replaced
        wholesale, because the lessons after the one that moved shift with it,
        and must hold at least one row. is_default false is VALIDATION_FAILED:
        make another schedule the default instead. A schedule with no rows cannot
        become it (EMPTY_BELL_SCHEDULE).
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_bell_schedule(self, request: DeleteBellScheduleRequest, ctx: RequestContext[DeleteBellScheduleRequest, DeleteBellScheduleResponse], /) -> DeleteBellScheduleResponse:
        """
        RESOURCE_IN_USE for the class default and for a schedule special days
        point at: deleting either would silently move those days onto another.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in bell_pb.desc().services if s.type_name == 'lessons.v2.BellService')

class BellServiceASGIApplication(ConnectASGIApplication[BellService]):
    def __init__(
        self,
        service: BellService | AsyncGenerator[BellService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/lessons.v2.BellService/ListBellSchedules": Endpoint.unary(
                    method=MethodInfo(
                        name="ListBellSchedules",
                        service_name="lessons.v2.BellService",
                        input=ListBellSchedulesRequest,
                        output=ListBellSchedulesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_bell_schedules,
                ),
                "/lessons.v2.BellService/GetBellSchedule": Endpoint.unary(
                    method=MethodInfo(
                        name="GetBellSchedule",
                        service_name="lessons.v2.BellService",
                        input=GetBellScheduleRequest,
                        output=GetBellScheduleResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_bell_schedule,
                ),
                "/lessons.v2.BellService/CreateBellSchedule": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateBellSchedule",
                        service_name="lessons.v2.BellService",
                        input=CreateBellScheduleRequest,
                        output=CreateBellScheduleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_bell_schedule,
                ),
                "/lessons.v2.BellService/UpdateBellSchedule": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateBellSchedule",
                        service_name="lessons.v2.BellService",
                        input=UpdateBellScheduleRequest,
                        output=UpdateBellScheduleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_bell_schedule,
                ),
                "/lessons.v2.BellService/DeleteBellSchedule": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteBellSchedule",
                        service_name="lessons.v2.BellService",
                        input=DeleteBellScheduleRequest,
                        output=DeleteBellScheduleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_bell_schedule,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.BellService"


class BellServiceClient(ConnectClient):
    async def list_bell_schedules(
        self,
        request: ListBellSchedulesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListBellSchedulesResponse:
        """
        Every schedule the class keeps («Обычное», «Сокращённое», «Суббота»),
        with the default marked.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListBellSchedules",
                service_name="lessons.v2.BellService",
                input=ListBellSchedulesRequest,
                output=ListBellSchedulesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_bell_schedule(
        self,
        request: GetBellScheduleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetBellScheduleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBellSchedule",
                service_name="lessons.v2.BellService",
                input=GetBellScheduleRequest,
                output=GetBellScheduleResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_bell_schedule(
        self,
        request: CreateBellScheduleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateBellScheduleResponse:
        """
        A new named schedule, with its rows if they come with it. It does not
        become the default: a shortened schedule exists to be pointed at by
        particular days. REST answers 201.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateBellSchedule",
                service_name="lessons.v2.BellService",
                input=CreateBellScheduleRequest,
                output=CreateBellScheduleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_bell_schedule(
        self,
        request: UpdateBellScheduleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdateBellScheduleResponse:
        """
        `update_mask` takes name, is_default and periods. Periods are replaced
        wholesale, because the lessons after the one that moved shift with it,
        and must hold at least one row. is_default false is VALIDATION_FAILED:
        make another schedule the default instead. A schedule with no rows cannot
        become it (EMPTY_BELL_SCHEDULE).
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateBellSchedule",
                service_name="lessons.v2.BellService",
                input=UpdateBellScheduleRequest,
                output=UpdateBellScheduleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_bell_schedule(
        self,
        request: DeleteBellScheduleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteBellScheduleResponse:
        """
        RESOURCE_IN_USE for the class default and for a schedule special days
        point at: deleting either would silently move those days onto another.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteBellSchedule",
                service_name="lessons.v2.BellService",
                input=DeleteBellScheduleRequest,
                output=DeleteBellScheduleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class BellServiceSync(Protocol):
    def list_bell_schedules(self, request: ListBellSchedulesRequest, ctx: RequestContext[ListBellSchedulesRequest, ListBellSchedulesResponse], /) -> ListBellSchedulesResponse:
        """
        Every schedule the class keeps («Обычное», «Сокращённое», «Суббота»),
        with the default marked.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_bell_schedule(self, request: GetBellScheduleRequest, ctx: RequestContext[GetBellScheduleRequest, GetBellScheduleResponse], /) -> GetBellScheduleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def create_bell_schedule(self, request: CreateBellScheduleRequest, ctx: RequestContext[CreateBellScheduleRequest, CreateBellScheduleResponse], /) -> CreateBellScheduleResponse:
        """
        A new named schedule, with its rows if they come with it. It does not
        become the default: a shortened schedule exists to be pointed at by
        particular days. REST answers 201.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def update_bell_schedule(self, request: UpdateBellScheduleRequest, ctx: RequestContext[UpdateBellScheduleRequest, UpdateBellScheduleResponse], /) -> UpdateBellScheduleResponse:
        """
        `update_mask` takes name, is_default and periods. Periods are replaced
        wholesale, because the lessons after the one that moved shift with it,
        and must hold at least one row. is_default false is VALIDATION_FAILED:
        make another schedule the default instead. A schedule with no rows cannot
        become it (EMPTY_BELL_SCHEDULE).
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_bell_schedule(self, request: DeleteBellScheduleRequest, ctx: RequestContext[DeleteBellScheduleRequest, DeleteBellScheduleResponse], /) -> DeleteBellScheduleResponse:
        """
        RESOURCE_IN_USE for the class default and for a schedule special days
        point at: deleting either would silently move those days onto another.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in bell_pb.desc().services if s.type_name == 'lessons.v2.BellService')

class BellServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: BellServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/lessons.v2.BellService/ListBellSchedules": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListBellSchedules",
                        service_name="lessons.v2.BellService",
                        input=ListBellSchedulesRequest,
                        output=ListBellSchedulesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_bell_schedules,
                ),
                "/lessons.v2.BellService/GetBellSchedule": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetBellSchedule",
                        service_name="lessons.v2.BellService",
                        input=GetBellScheduleRequest,
                        output=GetBellScheduleResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_bell_schedule,
                ),
                "/lessons.v2.BellService/CreateBellSchedule": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateBellSchedule",
                        service_name="lessons.v2.BellService",
                        input=CreateBellScheduleRequest,
                        output=CreateBellScheduleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_bell_schedule,
                ),
                "/lessons.v2.BellService/UpdateBellSchedule": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateBellSchedule",
                        service_name="lessons.v2.BellService",
                        input=UpdateBellScheduleRequest,
                        output=UpdateBellScheduleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_bell_schedule,
                ),
                "/lessons.v2.BellService/DeleteBellSchedule": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteBellSchedule",
                        service_name="lessons.v2.BellService",
                        input=DeleteBellScheduleRequest,
                        output=DeleteBellScheduleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_bell_schedule,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.BellService"


class BellServiceClientSync(ConnectClientSync):
    def list_bell_schedules(
        self,
        request: ListBellSchedulesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListBellSchedulesResponse:
        """
        Every schedule the class keeps («Обычное», «Сокращённое», «Суббота»),
        with the default marked.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListBellSchedules",
                service_name="lessons.v2.BellService",
                input=ListBellSchedulesRequest,
                output=ListBellSchedulesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def get_bell_schedule(
        self,
        request: GetBellScheduleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetBellScheduleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBellSchedule",
                service_name="lessons.v2.BellService",
                input=GetBellScheduleRequest,
                output=GetBellScheduleResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def create_bell_schedule(
        self,
        request: CreateBellScheduleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateBellScheduleResponse:
        """
        A new named schedule, with its rows if they come with it. It does not
        become the default: a shortened schedule exists to be pointed at by
        particular days. REST answers 201.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateBellSchedule",
                service_name="lessons.v2.BellService",
                input=CreateBellScheduleRequest,
                output=CreateBellScheduleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def update_bell_schedule(
        self,
        request: UpdateBellScheduleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdateBellScheduleResponse:
        """
        `update_mask` takes name, is_default and periods. Periods are replaced
        wholesale, because the lessons after the one that moved shift with it,
        and must hold at least one row. is_default false is VALIDATION_FAILED:
        make another schedule the default instead. A schedule with no rows cannot
        become it (EMPTY_BELL_SCHEDULE).
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateBellSchedule",
                service_name="lessons.v2.BellService",
                input=UpdateBellScheduleRequest,
                output=UpdateBellScheduleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_bell_schedule(
        self,
        request: DeleteBellScheduleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteBellScheduleResponse:
        """
        RESOURCE_IN_USE for the class default and for a schedule special days
        point at: deleting either would silently move those days onto another.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteBellSchedule",
                service_name="lessons.v2.BellService",
                input=DeleteBellScheduleRequest,
                output=DeleteBellScheduleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
