# Generated from lessons/v2/device.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.6.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from . import options_pb
from ...google.api import annotations_pb

if TYPE_CHECKING:
    from protobuf import DescFile


_CreateDeviceRequestFields: TypeAlias = Literal["code", "device_name"]

class CreateDeviceRequest(Message[_CreateDeviceRequestFields]):
    """
    ```proto
    message lessons.v2.CreateDeviceRequest
    ```

    Attributes:
        code:
            The class code or a personal code: 4 to 16 characters once control
            characters are dropped; case does not matter. v1: JoinRequest.code.

            ```proto
            string code = 1;
            ```
        device_name:
            What the person calls this phone, up to 120 characters, shown on
            «📱 Устройства». v1: JoinRequest.device_name.

            ```proto
            optional string device_name = 2;
            ```
    """

    __slots__ = ("code", "device_name")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            code: str = "",
            device_name: str | None = None,
        ) -> None:
            pass

        code: str
        device_name: str

_CreateDeviceResponseFields: TypeAlias = Literal["token", "class_id", "class_name", "school", "timezone", "diary"]

class CreateDeviceResponse(Message[_CreateDeviceResponseFields]):
    """
    ```proto
    message lessons.v2.CreateDeviceResponse
    ```

    Attributes:
        token:
            The device token, for `Authorization: Bearer`. Sent once: the server
            keeps only its hash.

            ```proto
            string token = 1;
            ```
        class_id:
            ```proto
            int32 class_id = 2;
            ```
        class_name:
            ```proto
            string class_name = 3;
            ```
        school:
            ```proto
            optional string school = 4;
            ```
        timezone:
            The class's IANA zone, e.g. "Europe/Moscow": where its days are cut.

            ```proto
            string timezone = 5;
            ```
        diary:
            The diary the class is bound to in the bot, when this server can reach
            it, so the phone signs in there without searching for its school.

            ```proto
            optional lessons.v2.DiaryBinding diary = 6;
            ```
    """

    __slots__ = ("token", "class_id", "class_name", "school", "timezone", "diary")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            token: str = "",
            class_id: int = 0,
            class_name: str = "",
            school: str | None = None,
            timezone: str = "",
            diary: DiaryBinding | None = None,
        ) -> None:
            pass

        token: str
        class_id: int
        class_name: str
        school: str
        timezone: str
        diary: DiaryBinding | None

_DiaryBindingFields: TypeAlias = Literal["provider", "region", "school_id", "school_name"]

class DiaryBinding(Message[_DiaryBindingFields]):
    """
    Which diary a class reads. v1: DiaryBindingOut.

    ```proto
    message lessons.v2.DiaryBinding
    ```

    Attributes:
        provider:
            A provider key, "petersburg" or "netschool" today: a string rather than
            an enum, so a provider added on the server reaches the phone with no
            change here (the design's decision 8).

            ```proto
            string provider = 1;
            ```
        region:
            The allow-list key, which is the region catalog's key; absent for
            Petersburg, which is one city's server.

            ```proto
            optional string region = 2;
            ```
        school_id:
            The diary's own school id («scid»), which the phone signs in with.

            ```proto
            optional int64 school_id = 3;
            ```
        school_name:
            ```proto
            optional string school_name = 4;
            ```
    """

    __slots__ = ("provider", "region", "school_id", "school_name")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            provider: str = "",
            region: str | None = None,
            school_id: int | None = None,
            school_name: str | None = None,
        ) -> None:
            pass

        provider: str
        region: str
        school_id: int
        school_name: str


_DESC = file_desc(
    b'\n\x17lessons/v2/device.proto\x12\nlessons.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x18lessons/v2/options.proto"_\n\x13CreateDeviceRequest\x12\x12\n\x04code\x18\x01 \x01(\tR\x04code\x12$\n\x0bdevice_name\x18\x02 \x01(\tH\x00R\ndeviceName\x88\x01\x01B\x0e\n\x0c_device_name"\xda\x01\n\x14CreateDeviceResponse\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n\x08class_id\x18\x02 \x01(\x05R\x07classId\x12\x1d\n\nclass_name\x18\x03 \x01(\tR\tclassName\x12\x1b\n\x06school\x18\x04 \x01(\tH\x00R\x06school\x88\x01\x01\x12\x1a\n\x08timezone\x18\x05 \x01(\tR\x08timezone\x12.\n\x05diary\x18\x06 \x01(\x0b2\x18.lessons.v2.DiaryBindingR\x05diaryB\t\n\x07_school"\xb8\x01\n\x0cDiaryBinding\x12\x1a\n\x08provider\x18\x01 \x01(\tR\x08provider\x12\x1b\n\x06region\x18\x02 \x01(\tH\x00R\x06region\x88\x01\x01\x12 \n\tschool_id\x18\x03 \x01(\x03H\x01R\x08schoolId\x88\x01\x01\x12$\n\x0bschool_name\x18\x04 \x01(\tH\x02R\nschoolName\x88\x01\x01B\t\n\x07_regionB\x0c\n\n_school_idB\x0e\n\x0c_school_name2~\n\rDeviceService\x12m\n\x0cCreateDevice\x12\x1f.lessons.v2.CreateDeviceRequest\x1a .lessons.v2.CreateDeviceResponse"\x1a\x88\xb5\x18\x01\x82\xd3\xe4\x93\x02\x10:\x01*"\x0b/v2/devicesB(\n$com.lumenpearson.lessons.contract.v2P\x01b\x06proto3',
    [
        annotations_pb.desc(),
        options_pb.desc(),
    ],
    {
        "CreateDeviceRequest": CreateDeviceRequest,
        "CreateDeviceResponse": CreateDeviceResponse,
        "DiaryBinding": DiaryBinding,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `lessons/v2/device.proto`."""
    return _DESC
