# Generated from lessons/v2/device.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import device_pb
from .device_pb import CreateDeviceRequest, CreateDeviceResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class DeviceService(Protocol):
    async def create_device(self, request: CreateDeviceRequest, ctx: RequestContext[CreateDeviceRequest, CreateDeviceResponse], /) -> CreateDeviceResponse:
        """
        Exchanges a code for a long-lived device token. The class code (eight
        characters) buys an anonymous, read-only token; a personal code from the
        bot's «📱 Подключить телефон» (ten characters, fifteen minutes, one phone)
        buys one already linked to the account that minted it. The class code is
        looked up first, and the lengths keep the two apart. REST answers 201.

        Refusals: JOIN_CODE_UNKNOWN, which is counted against the caller;
        CLASS_INVITE_ONLY and DEVICE_LIMIT_REACHED, which are not, because the
        caller had a real code; THROTTLED.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in device_pb.desc().services if s.type_name == 'lessons.v2.DeviceService')

class DeviceServiceASGIApplication(ConnectASGIApplication[DeviceService]):
    def __init__(
        self,
        service: DeviceService | AsyncGenerator[DeviceService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/lessons.v2.DeviceService/CreateDevice": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateDevice",
                        service_name="lessons.v2.DeviceService",
                        input=CreateDeviceRequest,
                        output=CreateDeviceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_device,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.DeviceService"


class DeviceServiceClient(ConnectClient):
    async def create_device(
        self,
        request: CreateDeviceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateDeviceResponse:
        """
        Exchanges a code for a long-lived device token. The class code (eight
        characters) buys an anonymous, read-only token; a personal code from the
        bot's «📱 Подключить телефон» (ten characters, fifteen minutes, one phone)
        buys one already linked to the account that minted it. The class code is
        looked up first, and the lengths keep the two apart. REST answers 201.

        Refusals: JOIN_CODE_UNKNOWN, which is counted against the caller;
        CLASS_INVITE_ONLY and DEVICE_LIMIT_REACHED, which are not, because the
        caller had a real code; THROTTLED.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateDevice",
                service_name="lessons.v2.DeviceService",
                input=CreateDeviceRequest,
                output=CreateDeviceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class DeviceServiceSync(Protocol):
    def create_device(self, request: CreateDeviceRequest, ctx: RequestContext[CreateDeviceRequest, CreateDeviceResponse], /) -> CreateDeviceResponse:
        """
        Exchanges a code for a long-lived device token. The class code (eight
        characters) buys an anonymous, read-only token; a personal code from the
        bot's «📱 Подключить телефон» (ten characters, fifteen minutes, one phone)
        buys one already linked to the account that minted it. The class code is
        looked up first, and the lengths keep the two apart. REST answers 201.

        Refusals: JOIN_CODE_UNKNOWN, which is counted against the caller;
        CLASS_INVITE_ONLY and DEVICE_LIMIT_REACHED, which are not, because the
        caller had a real code; THROTTLED.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in device_pb.desc().services if s.type_name == 'lessons.v2.DeviceService')

class DeviceServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: DeviceServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/lessons.v2.DeviceService/CreateDevice": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateDevice",
                        service_name="lessons.v2.DeviceService",
                        input=CreateDeviceRequest,
                        output=CreateDeviceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_device,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.DeviceService"


class DeviceServiceClientSync(ConnectClientSync):
    def create_device(
        self,
        request: CreateDeviceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateDeviceResponse:
        """
        Exchanges a code for a long-lived device token. The class code (eight
        characters) buys an anonymous, read-only token; a personal code from the
        bot's «📱 Подключить телефон» (ten characters, fifteen minutes, one phone)
        buys one already linked to the account that minted it. The class code is
        looked up first, and the lengths keep the two apart. REST answers 201.

        Refusals: JOIN_CODE_UNKNOWN, which is counted against the caller;
        CLASS_INVITE_ONLY and DEVICE_LIMIT_REACHED, which are not, because the
        caller had a real code; THROTTLED.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateDevice",
                service_name="lessons.v2.DeviceService",
                input=CreateDeviceRequest,
                output=CreateDeviceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
