# Generated from lessons/v2/diary.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import diary_pb
from .diary_pb import BatchUpdateCorrectionsRequest, BatchUpdateCorrectionsResponse, ClearCorrectionsRequest, ClearCorrectionsResponse, CreateDiarySessionRequest, CreateDiarySessionResponse, DeleteDiarySessionRequest, DeleteDiarySessionResponse, GetDiaryCapabilitiesRequest, GetDiaryCapabilitiesResponse, ListCorrectionsRequest, ListCorrectionsResponse, ListDiaryHomeworkRequest, ListDiaryHomeworkResponse, ListDiarySubjectsRequest, ListDiarySubjectsResponse, ListMarksRequest, ListMarksResponse, ListPeriodsRequest, ListPeriodsResponse, ListScheduleDaysRequest, ListScheduleDaysResponse, ListStudentsRequest, ListStudentsResponse, ListTeachersRequest, ListTeachersResponse, ListTurnstileEventsRequest, ListTurnstileEventsResponse, ResetCorrectionsRequest, ResetCorrectionsResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class DiaryService(Protocol):
    async def get_diary_capabilities(self, request: GetDiaryCapabilitiesRequest, ctx: RequestContext[GetDiaryCapabilitiesRequest, GetDiaryCapabilitiesResponse], /) -> GetDiaryCapabilitiesResponse:
        """
        What this server's diary can do, asked before the phone shows a sign-in
        form: whether it runs at all, and for each provider the regions, the ways
        in, and the data it has. Anonymous and database-free.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def create_diary_session(self, request: CreateDiarySessionRequest, ctx: RequestContext[CreateDiarySessionRequest, CreateDiarySessionResponse], /) -> CreateDiarySessionResponse:
        """
        Keeps a session the phone opened with the diary itself, and answers a
        diary token of ours. The session is read with once, from this server's
        address (that read is the check), then sealed, and it is never echoed
        back, not even in a refusal. The caller is counted under v1's
        /diary/session limits. REST answers 201.

        Refusals:
        - DIARY_DISABLED and DIARY_UNAVAILABLE: not counted, because nothing
          judged the session;
        - DIARY_CREDENTIALS_REJECTED, DIARY_NO_STUDENTS and
          DIARY_UPSTREAM_UNREADABLE: counted;
        - VALIDATION_FAILED: a region outside the allow-list, before any
          upstream call;
        - THROTTLED.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_diary_session(self, request: DeleteDiarySessionRequest, ctx: RequestContext[DeleteDiarySessionRequest, DeleteDiarySessionResponse], /) -> DeleteDiarySessionResponse:
        """
        Signs this session out: the token stops working and the sealed upstream
        session goes.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_students(self, request: ListStudentsRequest, ctx: RequestContext[ListStudentsRequest, ListStudentsResponse], /) -> ListStudentsResponse:
        """
        Every pupil this diary account may see: one, for most parents.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_schedule_days(self, request: ListScheduleDaysRequest, ctx: RequestContext[ListScheduleDaysRequest, ListScheduleDaysResponse], /) -> ListScheduleDaysResponse:
        """
        A pupil's lessons, day by day, with the family's corrections laid over
        them: a day without lessons is not listed, the days come in date order,
        and each day's lessons in the order the diary is read in. The range is
        the diary's today and 14 days on when unset, and spans 62 days at most;
        one it refuses is
        VALIDATION_FAILED on start_date or end_date before the diary is asked
        anything, here and on every method below that takes a range. A student
        id this session's diary does not list is RESOURCE_NOT_FOUND, on every
        method below: an id from another family must reach nothing. A method
        whose DIARY_FEATURE the session's provider does not declare answers
        FEATURE_UNSUPPORTED before the diary is asked anything.
        DIARY_FEATURE_SCHEDULE.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_diary_homework(self, request: ListDiaryHomeworkRequest, ctx: RequestContext[ListDiaryHomeworkRequest, ListDiaryHomeworkResponse], /) -> ListDiaryHomeworkResponse:
        """
        A pupil's homework by due date, with corrections laid over it. Named for
        the diary because HomeworkService's ListHomework is the class's.
        DIARY_FEATURE_HOMEWORK.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_marks(self, request: ListMarksRequest, ctx: RequestContext[ListMarksRequest, ListMarksResponse], /) -> ListMarksResponse:
        """
        A pupil's marks, absences and lateness, which a diary files together.
        Never corrected: a family rewriting a mark would be producing a false
        record that looks official. DIARY_FEATURE_MARKS.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_periods(self, request: ListPeriodsRequest, ctx: RequestContext[ListPeriodsRequest, ListPeriodsResponse], /) -> ListPeriodsResponse:
        """
        A pupil's quarters or terms as the diary has them. DIARY_FEATURE_PERIODS.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_diary_subjects(self, request: ListDiarySubjectsRequest, ctx: RequestContext[ListDiarySubjectsRequest, ListDiarySubjectsResponse], /) -> ListDiarySubjectsResponse:
        """
        The subjects of a period, the current one when none is named. Named for
        the diary because SubjectService's ListSubjects is the class's.
        DIARY_FEATURE_SUBJECTS.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_teachers(self, request: ListTeachersRequest, ctx: RequestContext[ListTeachersRequest, ListTeachersResponse], /) -> ListTeachersResponse:
        """
        DIARY_FEATURE_TEACHERS.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_turnstile_events(self, request: ListTurnstileEventsRequest, ctx: RequestContext[ListTurnstileEventsRequest, ListTurnstileEventsResponse], /) -> ListTurnstileEventsResponse:
        """
        Turnstile entries and exits, newest first: what v1's /attendance served.
        Absences and lateness are not here; a diary files those with the marks.
        DIARY_FEATURE_TURNSTILE.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_corrections(self, request: ListCorrectionsRequest, ctx: RequestContext[ListCorrectionsRequest, ListCorrectionsResponse], /) -> ListCorrectionsResponse:
        """
        Every correction anybody who sees this pupil made, both parents' alike;
        no row says whose. By target, then field; none for a pupil who can have
        none.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def batch_update_corrections(self, request: BatchUpdateCorrectionsRequest, ctx: RequestContext[BatchUpdateCorrectionsRequest, BatchUpdateCorrectionsResponse], /) -> BatchUpdateCorrectionsResponse:
        """
        Writes or replaces corrections, all or none, and answers each as it is
        stored once all are written, in the order asked. Each target is the
        string a read handed down, echoed back; the last writer wins, `original`
        included, and a target and field named twice in one request keep the
        later. At most 200 corrections a request. CORRECTIONS_UNAVAILABLE for a
        pupil who can have none. VALIDATION_FAILED, before the diary is asked
        anything: on `corrections` past 200, or naming the first correction
        refused, `corrections[i].target`, `.field` or `.value` with i counted
        from 0, for a target this server would never produce, a field that
        cannot be corrected, or an empty value where one is required.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def reset_corrections(self, request: ResetCorrectionsRequest, ctx: RequestContext[ResetCorrectionsRequest, ResetCorrectionsResponse], /) -> ResetCorrectionsResponse:
        """
        Takes the named corrections off, for everyone who sees the pupil, all or
        none. It answers the same whether or not there was one, and for a pupil
        who can have none: «no correction here» is what was asked for. At most
        200 a request, as BatchUpdateCorrections. A POST with a body, because a
        target is free text, and a value that must match byte for byte does not
        travel in a URL. VALIDATION_FAILED, before the diary is asked anything:
        on `corrections` past 200 keys, or naming the first one refused,
        `corrections[i].target` or `.field` with i counted from 0, for an empty
        or overlong key.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def clear_corrections(self, request: ClearCorrectionsRequest, ctx: RequestContext[ClearCorrectionsRequest, ClearCorrectionsResponse], /) -> ClearCorrectionsResponse:
        """
        Takes every correction for this pupil off, and nothing of any other's.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in diary_pb.desc().services if s.type_name == 'lessons.v2.DiaryService')

class DiaryServiceASGIApplication(ConnectASGIApplication[DiaryService]):
    def __init__(
        self,
        service: DiaryService | AsyncGenerator[DiaryService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/lessons.v2.DiaryService/GetDiaryCapabilities": Endpoint.unary(
                    method=MethodInfo(
                        name="GetDiaryCapabilities",
                        service_name="lessons.v2.DiaryService",
                        input=GetDiaryCapabilitiesRequest,
                        output=GetDiaryCapabilitiesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_diary_capabilities,
                ),
                "/lessons.v2.DiaryService/CreateDiarySession": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateDiarySession",
                        service_name="lessons.v2.DiaryService",
                        input=CreateDiarySessionRequest,
                        output=CreateDiarySessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_diary_session,
                ),
                "/lessons.v2.DiaryService/DeleteDiarySession": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteDiarySession",
                        service_name="lessons.v2.DiaryService",
                        input=DeleteDiarySessionRequest,
                        output=DeleteDiarySessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_diary_session,
                ),
                "/lessons.v2.DiaryService/ListStudents": Endpoint.unary(
                    method=MethodInfo(
                        name="ListStudents",
                        service_name="lessons.v2.DiaryService",
                        input=ListStudentsRequest,
                        output=ListStudentsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_students,
                ),
                "/lessons.v2.DiaryService/ListScheduleDays": Endpoint.unary(
                    method=MethodInfo(
                        name="ListScheduleDays",
                        service_name="lessons.v2.DiaryService",
                        input=ListScheduleDaysRequest,
                        output=ListScheduleDaysResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_schedule_days,
                ),
                "/lessons.v2.DiaryService/ListDiaryHomework": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDiaryHomework",
                        service_name="lessons.v2.DiaryService",
                        input=ListDiaryHomeworkRequest,
                        output=ListDiaryHomeworkResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_diary_homework,
                ),
                "/lessons.v2.DiaryService/ListMarks": Endpoint.unary(
                    method=MethodInfo(
                        name="ListMarks",
                        service_name="lessons.v2.DiaryService",
                        input=ListMarksRequest,
                        output=ListMarksResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_marks,
                ),
                "/lessons.v2.DiaryService/ListPeriods": Endpoint.unary(
                    method=MethodInfo(
                        name="ListPeriods",
                        service_name="lessons.v2.DiaryService",
                        input=ListPeriodsRequest,
                        output=ListPeriodsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_periods,
                ),
                "/lessons.v2.DiaryService/ListDiarySubjects": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDiarySubjects",
                        service_name="lessons.v2.DiaryService",
                        input=ListDiarySubjectsRequest,
                        output=ListDiarySubjectsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_diary_subjects,
                ),
                "/lessons.v2.DiaryService/ListTeachers": Endpoint.unary(
                    method=MethodInfo(
                        name="ListTeachers",
                        service_name="lessons.v2.DiaryService",
                        input=ListTeachersRequest,
                        output=ListTeachersResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_teachers,
                ),
                "/lessons.v2.DiaryService/ListTurnstileEvents": Endpoint.unary(
                    method=MethodInfo(
                        name="ListTurnstileEvents",
                        service_name="lessons.v2.DiaryService",
                        input=ListTurnstileEventsRequest,
                        output=ListTurnstileEventsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_turnstile_events,
                ),
                "/lessons.v2.DiaryService/ListCorrections": Endpoint.unary(
                    method=MethodInfo(
                        name="ListCorrections",
                        service_name="lessons.v2.DiaryService",
                        input=ListCorrectionsRequest,
                        output=ListCorrectionsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_corrections,
                ),
                "/lessons.v2.DiaryService/BatchUpdateCorrections": Endpoint.unary(
                    method=MethodInfo(
                        name="BatchUpdateCorrections",
                        service_name="lessons.v2.DiaryService",
                        input=BatchUpdateCorrectionsRequest,
                        output=BatchUpdateCorrectionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.batch_update_corrections,
                ),
                "/lessons.v2.DiaryService/ResetCorrections": Endpoint.unary(
                    method=MethodInfo(
                        name="ResetCorrections",
                        service_name="lessons.v2.DiaryService",
                        input=ResetCorrectionsRequest,
                        output=ResetCorrectionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.reset_corrections,
                ),
                "/lessons.v2.DiaryService/ClearCorrections": Endpoint.unary(
                    method=MethodInfo(
                        name="ClearCorrections",
                        service_name="lessons.v2.DiaryService",
                        input=ClearCorrectionsRequest,
                        output=ClearCorrectionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.clear_corrections,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.DiaryService"


class DiaryServiceClient(ConnectClient):
    async def get_diary_capabilities(
        self,
        request: GetDiaryCapabilitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetDiaryCapabilitiesResponse:
        """
        What this server's diary can do, asked before the phone shows a sign-in
        form: whether it runs at all, and for each provider the regions, the ways
        in, and the data it has. Anonymous and database-free.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDiaryCapabilities",
                service_name="lessons.v2.DiaryService",
                input=GetDiaryCapabilitiesRequest,
                output=GetDiaryCapabilitiesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_diary_session(
        self,
        request: CreateDiarySessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateDiarySessionResponse:
        """
        Keeps a session the phone opened with the diary itself, and answers a
        diary token of ours. The session is read with once, from this server's
        address (that read is the check), then sealed, and it is never echoed
        back, not even in a refusal. The caller is counted under v1's
        /diary/session limits. REST answers 201.

        Refusals:
        - DIARY_DISABLED and DIARY_UNAVAILABLE: not counted, because nothing
          judged the session;
        - DIARY_CREDENTIALS_REJECTED, DIARY_NO_STUDENTS and
          DIARY_UPSTREAM_UNREADABLE: counted;
        - VALIDATION_FAILED: a region outside the allow-list, before any
          upstream call;
        - THROTTLED.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateDiarySession",
                service_name="lessons.v2.DiaryService",
                input=CreateDiarySessionRequest,
                output=CreateDiarySessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_diary_session(
        self,
        request: DeleteDiarySessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteDiarySessionResponse:
        """
        Signs this session out: the token stops working and the sealed upstream
        session goes.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteDiarySession",
                service_name="lessons.v2.DiaryService",
                input=DeleteDiarySessionRequest,
                output=DeleteDiarySessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_students(
        self,
        request: ListStudentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListStudentsResponse:
        """
        Every pupil this diary account may see: one, for most parents.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStudents",
                service_name="lessons.v2.DiaryService",
                input=ListStudentsRequest,
                output=ListStudentsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def list_schedule_days(
        self,
        request: ListScheduleDaysRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListScheduleDaysResponse:
        """
        A pupil's lessons, day by day, with the family's corrections laid over
        them: a day without lessons is not listed, the days come in date order,
        and each day's lessons in the order the diary is read in. The range is
        the diary's today and 14 days on when unset, and spans 62 days at most;
        one it refuses is
        VALIDATION_FAILED on start_date or end_date before the diary is asked
        anything, here and on every method below that takes a range. A student
        id this session's diary does not list is RESOURCE_NOT_FOUND, on every
        method below: an id from another family must reach nothing. A method
        whose DIARY_FEATURE the session's provider does not declare answers
        FEATURE_UNSUPPORTED before the diary is asked anything.
        DIARY_FEATURE_SCHEDULE.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListScheduleDays",
                service_name="lessons.v2.DiaryService",
                input=ListScheduleDaysRequest,
                output=ListScheduleDaysResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def list_diary_homework(
        self,
        request: ListDiaryHomeworkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListDiaryHomeworkResponse:
        """
        A pupil's homework by due date, with corrections laid over it. Named for
        the diary because HomeworkService's ListHomework is the class's.
        DIARY_FEATURE_HOMEWORK.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDiaryHomework",
                service_name="lessons.v2.DiaryService",
                input=ListDiaryHomeworkRequest,
                output=ListDiaryHomeworkResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def list_marks(
        self,
        request: ListMarksRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListMarksResponse:
        """
        A pupil's marks, absences and lateness, which a diary files together.
        Never corrected: a family rewriting a mark would be producing a false
        record that looks official. DIARY_FEATURE_MARKS.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListMarks",
                service_name="lessons.v2.DiaryService",
                input=ListMarksRequest,
                output=ListMarksResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def list_periods(
        self,
        request: ListPeriodsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListPeriodsResponse:
        """
        A pupil's quarters or terms as the diary has them. DIARY_FEATURE_PERIODS.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPeriods",
                service_name="lessons.v2.DiaryService",
                input=ListPeriodsRequest,
                output=ListPeriodsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def list_diary_subjects(
        self,
        request: ListDiarySubjectsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListDiarySubjectsResponse:
        """
        The subjects of a period, the current one when none is named. Named for
        the diary because SubjectService's ListSubjects is the class's.
        DIARY_FEATURE_SUBJECTS.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDiarySubjects",
                service_name="lessons.v2.DiaryService",
                input=ListDiarySubjectsRequest,
                output=ListDiarySubjectsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def list_teachers(
        self,
        request: ListTeachersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListTeachersResponse:
        """
        DIARY_FEATURE_TEACHERS.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTeachers",
                service_name="lessons.v2.DiaryService",
                input=ListTeachersRequest,
                output=ListTeachersResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def list_turnstile_events(
        self,
        request: ListTurnstileEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListTurnstileEventsResponse:
        """
        Turnstile entries and exits, newest first: what v1's /attendance served.
        Absences and lateness are not here; a diary files those with the marks.
        DIARY_FEATURE_TURNSTILE.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTurnstileEvents",
                service_name="lessons.v2.DiaryService",
                input=ListTurnstileEventsRequest,
                output=ListTurnstileEventsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def list_corrections(
        self,
        request: ListCorrectionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListCorrectionsResponse:
        """
        Every correction anybody who sees this pupil made, both parents' alike;
        no row says whose. By target, then field; none for a pupil who can have
        none.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCorrections",
                service_name="lessons.v2.DiaryService",
                input=ListCorrectionsRequest,
                output=ListCorrectionsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def batch_update_corrections(
        self,
        request: BatchUpdateCorrectionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchUpdateCorrectionsResponse:
        """
        Writes or replaces corrections, all or none, and answers each as it is
        stored once all are written, in the order asked. Each target is the
        string a read handed down, echoed back; the last writer wins, `original`
        included, and a target and field named twice in one request keep the
        later. At most 200 corrections a request. CORRECTIONS_UNAVAILABLE for a
        pupil who can have none. VALIDATION_FAILED, before the diary is asked
        anything: on `corrections` past 200, or naming the first correction
        refused, `corrections[i].target`, `.field` or `.value` with i counted
        from 0, for a target this server would never produce, a field that
        cannot be corrected, or an empty value where one is required.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchUpdateCorrections",
                service_name="lessons.v2.DiaryService",
                input=BatchUpdateCorrectionsRequest,
                output=BatchUpdateCorrectionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def reset_corrections(
        self,
        request: ResetCorrectionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ResetCorrectionsResponse:
        """
        Takes the named corrections off, for everyone who sees the pupil, all or
        none. It answers the same whether or not there was one, and for a pupil
        who can have none: «no correction here» is what was asked for. At most
        200 a request, as BatchUpdateCorrections. A POST with a body, because a
        target is free text, and a value that must match byte for byte does not
        travel in a URL. VALIDATION_FAILED, before the diary is asked anything:
        on `corrections` past 200 keys, or naming the first one refused,
        `corrections[i].target` or `.field` with i counted from 0, for an empty
        or overlong key.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ResetCorrections",
                service_name="lessons.v2.DiaryService",
                input=ResetCorrectionsRequest,
                output=ResetCorrectionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def clear_corrections(
        self,
        request: ClearCorrectionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ClearCorrectionsResponse:
        """
        Takes every correction for this pupil off, and nothing of any other's.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ClearCorrections",
                service_name="lessons.v2.DiaryService",
                input=ClearCorrectionsRequest,
                output=ClearCorrectionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class DiaryServiceSync(Protocol):
    def get_diary_capabilities(self, request: GetDiaryCapabilitiesRequest, ctx: RequestContext[GetDiaryCapabilitiesRequest, GetDiaryCapabilitiesResponse], /) -> GetDiaryCapabilitiesResponse:
        """
        What this server's diary can do, asked before the phone shows a sign-in
        form: whether it runs at all, and for each provider the regions, the ways
        in, and the data it has. Anonymous and database-free.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def create_diary_session(self, request: CreateDiarySessionRequest, ctx: RequestContext[CreateDiarySessionRequest, CreateDiarySessionResponse], /) -> CreateDiarySessionResponse:
        """
        Keeps a session the phone opened with the diary itself, and answers a
        diary token of ours. The session is read with once, from this server's
        address (that read is the check), then sealed, and it is never echoed
        back, not even in a refusal. The caller is counted under v1's
        /diary/session limits. REST answers 201.

        Refusals:
        - DIARY_DISABLED and DIARY_UNAVAILABLE: not counted, because nothing
          judged the session;
        - DIARY_CREDENTIALS_REJECTED, DIARY_NO_STUDENTS and
          DIARY_UPSTREAM_UNREADABLE: counted;
        - VALIDATION_FAILED: a region outside the allow-list, before any
          upstream call;
        - THROTTLED.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_diary_session(self, request: DeleteDiarySessionRequest, ctx: RequestContext[DeleteDiarySessionRequest, DeleteDiarySessionResponse], /) -> DeleteDiarySessionResponse:
        """
        Signs this session out: the token stops working and the sealed upstream
        session goes.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_students(self, request: ListStudentsRequest, ctx: RequestContext[ListStudentsRequest, ListStudentsResponse], /) -> ListStudentsResponse:
        """
        Every pupil this diary account may see: one, for most parents.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_schedule_days(self, request: ListScheduleDaysRequest, ctx: RequestContext[ListScheduleDaysRequest, ListScheduleDaysResponse], /) -> ListScheduleDaysResponse:
        """
        A pupil's lessons, day by day, with the family's corrections laid over
        them: a day without lessons is not listed, the days come in date order,
        and each day's lessons in the order the diary is read in. The range is
        the diary's today and 14 days on when unset, and spans 62 days at most;
        one it refuses is
        VALIDATION_FAILED on start_date or end_date before the diary is asked
        anything, here and on every method below that takes a range. A student
        id this session's diary does not list is RESOURCE_NOT_FOUND, on every
        method below: an id from another family must reach nothing. A method
        whose DIARY_FEATURE the session's provider does not declare answers
        FEATURE_UNSUPPORTED before the diary is asked anything.
        DIARY_FEATURE_SCHEDULE.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_diary_homework(self, request: ListDiaryHomeworkRequest, ctx: RequestContext[ListDiaryHomeworkRequest, ListDiaryHomeworkResponse], /) -> ListDiaryHomeworkResponse:
        """
        A pupil's homework by due date, with corrections laid over it. Named for
        the diary because HomeworkService's ListHomework is the class's.
        DIARY_FEATURE_HOMEWORK.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_marks(self, request: ListMarksRequest, ctx: RequestContext[ListMarksRequest, ListMarksResponse], /) -> ListMarksResponse:
        """
        A pupil's marks, absences and lateness, which a diary files together.
        Never corrected: a family rewriting a mark would be producing a false
        record that looks official. DIARY_FEATURE_MARKS.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_periods(self, request: ListPeriodsRequest, ctx: RequestContext[ListPeriodsRequest, ListPeriodsResponse], /) -> ListPeriodsResponse:
        """
        A pupil's quarters or terms as the diary has them. DIARY_FEATURE_PERIODS.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_diary_subjects(self, request: ListDiarySubjectsRequest, ctx: RequestContext[ListDiarySubjectsRequest, ListDiarySubjectsResponse], /) -> ListDiarySubjectsResponse:
        """
        The subjects of a period, the current one when none is named. Named for
        the diary because SubjectService's ListSubjects is the class's.
        DIARY_FEATURE_SUBJECTS.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_teachers(self, request: ListTeachersRequest, ctx: RequestContext[ListTeachersRequest, ListTeachersResponse], /) -> ListTeachersResponse:
        """
        DIARY_FEATURE_TEACHERS.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_turnstile_events(self, request: ListTurnstileEventsRequest, ctx: RequestContext[ListTurnstileEventsRequest, ListTurnstileEventsResponse], /) -> ListTurnstileEventsResponse:
        """
        Turnstile entries and exits, newest first: what v1's /attendance served.
        Absences and lateness are not here; a diary files those with the marks.
        DIARY_FEATURE_TURNSTILE.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_corrections(self, request: ListCorrectionsRequest, ctx: RequestContext[ListCorrectionsRequest, ListCorrectionsResponse], /) -> ListCorrectionsResponse:
        """
        Every correction anybody who sees this pupil made, both parents' alike;
        no row says whose. By target, then field; none for a pupil who can have
        none.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def batch_update_corrections(self, request: BatchUpdateCorrectionsRequest, ctx: RequestContext[BatchUpdateCorrectionsRequest, BatchUpdateCorrectionsResponse], /) -> BatchUpdateCorrectionsResponse:
        """
        Writes or replaces corrections, all or none, and answers each as it is
        stored once all are written, in the order asked. Each target is the
        string a read handed down, echoed back; the last writer wins, `original`
        included, and a target and field named twice in one request keep the
        later. At most 200 corrections a request. CORRECTIONS_UNAVAILABLE for a
        pupil who can have none. VALIDATION_FAILED, before the diary is asked
        anything: on `corrections` past 200, or naming the first correction
        refused, `corrections[i].target`, `.field` or `.value` with i counted
        from 0, for a target this server would never produce, a field that
        cannot be corrected, or an empty value where one is required.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def reset_corrections(self, request: ResetCorrectionsRequest, ctx: RequestContext[ResetCorrectionsRequest, ResetCorrectionsResponse], /) -> ResetCorrectionsResponse:
        """
        Takes the named corrections off, for everyone who sees the pupil, all or
        none. It answers the same whether or not there was one, and for a pupil
        who can have none: «no correction here» is what was asked for. At most
        200 a request, as BatchUpdateCorrections. A POST with a body, because a
        target is free text, and a value that must match byte for byte does not
        travel in a URL. VALIDATION_FAILED, before the diary is asked anything:
        on `corrections` past 200 keys, or naming the first one refused,
        `corrections[i].target` or `.field` with i counted from 0, for an empty
        or overlong key.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def clear_corrections(self, request: ClearCorrectionsRequest, ctx: RequestContext[ClearCorrectionsRequest, ClearCorrectionsResponse], /) -> ClearCorrectionsResponse:
        """
        Takes every correction for this pupil off, and nothing of any other's.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in diary_pb.desc().services if s.type_name == 'lessons.v2.DiaryService')

class DiaryServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: DiaryServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/lessons.v2.DiaryService/GetDiaryCapabilities": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetDiaryCapabilities",
                        service_name="lessons.v2.DiaryService",
                        input=GetDiaryCapabilitiesRequest,
                        output=GetDiaryCapabilitiesResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_diary_capabilities,
                ),
                "/lessons.v2.DiaryService/CreateDiarySession": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateDiarySession",
                        service_name="lessons.v2.DiaryService",
                        input=CreateDiarySessionRequest,
                        output=CreateDiarySessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_diary_session,
                ),
                "/lessons.v2.DiaryService/DeleteDiarySession": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteDiarySession",
                        service_name="lessons.v2.DiaryService",
                        input=DeleteDiarySessionRequest,
                        output=DeleteDiarySessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_diary_session,
                ),
                "/lessons.v2.DiaryService/ListStudents": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListStudents",
                        service_name="lessons.v2.DiaryService",
                        input=ListStudentsRequest,
                        output=ListStudentsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_students,
                ),
                "/lessons.v2.DiaryService/ListScheduleDays": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListScheduleDays",
                        service_name="lessons.v2.DiaryService",
                        input=ListScheduleDaysRequest,
                        output=ListScheduleDaysResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_schedule_days,
                ),
                "/lessons.v2.DiaryService/ListDiaryHomework": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDiaryHomework",
                        service_name="lessons.v2.DiaryService",
                        input=ListDiaryHomeworkRequest,
                        output=ListDiaryHomeworkResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_diary_homework,
                ),
                "/lessons.v2.DiaryService/ListMarks": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListMarks",
                        service_name="lessons.v2.DiaryService",
                        input=ListMarksRequest,
                        output=ListMarksResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_marks,
                ),
                "/lessons.v2.DiaryService/ListPeriods": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListPeriods",
                        service_name="lessons.v2.DiaryService",
                        input=ListPeriodsRequest,
                        output=ListPeriodsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_periods,
                ),
                "/lessons.v2.DiaryService/ListDiarySubjects": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDiarySubjects",
                        service_name="lessons.v2.DiaryService",
                        input=ListDiarySubjectsRequest,
                        output=ListDiarySubjectsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_diary_subjects,
                ),
                "/lessons.v2.DiaryService/ListTeachers": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListTeachers",
                        service_name="lessons.v2.DiaryService",
                        input=ListTeachersRequest,
                        output=ListTeachersResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_teachers,
                ),
                "/lessons.v2.DiaryService/ListTurnstileEvents": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListTurnstileEvents",
                        service_name="lessons.v2.DiaryService",
                        input=ListTurnstileEventsRequest,
                        output=ListTurnstileEventsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_turnstile_events,
                ),
                "/lessons.v2.DiaryService/ListCorrections": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListCorrections",
                        service_name="lessons.v2.DiaryService",
                        input=ListCorrectionsRequest,
                        output=ListCorrectionsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_corrections,
                ),
                "/lessons.v2.DiaryService/BatchUpdateCorrections": EndpointSync.unary(
                    method=MethodInfo(
                        name="BatchUpdateCorrections",
                        service_name="lessons.v2.DiaryService",
                        input=BatchUpdateCorrectionsRequest,
                        output=BatchUpdateCorrectionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.batch_update_corrections,
                ),
                "/lessons.v2.DiaryService/ResetCorrections": EndpointSync.unary(
                    method=MethodInfo(
                        name="ResetCorrections",
                        service_name="lessons.v2.DiaryService",
                        input=ResetCorrectionsRequest,
                        output=ResetCorrectionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.reset_corrections,
                ),
                "/lessons.v2.DiaryService/ClearCorrections": EndpointSync.unary(
                    method=MethodInfo(
                        name="ClearCorrections",
                        service_name="lessons.v2.DiaryService",
                        input=ClearCorrectionsRequest,
                        output=ClearCorrectionsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.clear_corrections,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.DiaryService"


class DiaryServiceClientSync(ConnectClientSync):
    def get_diary_capabilities(
        self,
        request: GetDiaryCapabilitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetDiaryCapabilitiesResponse:
        """
        What this server's diary can do, asked before the phone shows a sign-in
        form: whether it runs at all, and for each provider the regions, the ways
        in, and the data it has. Anonymous and database-free.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDiaryCapabilities",
                service_name="lessons.v2.DiaryService",
                input=GetDiaryCapabilitiesRequest,
                output=GetDiaryCapabilitiesResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def create_diary_session(
        self,
        request: CreateDiarySessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateDiarySessionResponse:
        """
        Keeps a session the phone opened with the diary itself, and answers a
        diary token of ours. The session is read with once, from this server's
        address (that read is the check), then sealed, and it is never echoed
        back, not even in a refusal. The caller is counted under v1's
        /diary/session limits. REST answers 201.

        Refusals:
        - DIARY_DISABLED and DIARY_UNAVAILABLE: not counted, because nothing
          judged the session;
        - DIARY_CREDENTIALS_REJECTED, DIARY_NO_STUDENTS and
          DIARY_UPSTREAM_UNREADABLE: counted;
        - VALIDATION_FAILED: a region outside the allow-list, before any
          upstream call;
        - THROTTLED.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateDiarySession",
                service_name="lessons.v2.DiaryService",
                input=CreateDiarySessionRequest,
                output=CreateDiarySessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_diary_session(
        self,
        request: DeleteDiarySessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteDiarySessionResponse:
        """
        Signs this session out: the token stops working and the sealed upstream
        session goes.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteDiarySession",
                service_name="lessons.v2.DiaryService",
                input=DeleteDiarySessionRequest,
                output=DeleteDiarySessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_students(
        self,
        request: ListStudentsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListStudentsResponse:
        """
        Every pupil this diary account may see: one, for most parents.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStudents",
                service_name="lessons.v2.DiaryService",
                input=ListStudentsRequest,
                output=ListStudentsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def list_schedule_days(
        self,
        request: ListScheduleDaysRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListScheduleDaysResponse:
        """
        A pupil's lessons, day by day, with the family's corrections laid over
        them: a day without lessons is not listed, the days come in date order,
        and each day's lessons in the order the diary is read in. The range is
        the diary's today and 14 days on when unset, and spans 62 days at most;
        one it refuses is
        VALIDATION_FAILED on start_date or end_date before the diary is asked
        anything, here and on every method below that takes a range. A student
        id this session's diary does not list is RESOURCE_NOT_FOUND, on every
        method below: an id from another family must reach nothing. A method
        whose DIARY_FEATURE the session's provider does not declare answers
        FEATURE_UNSUPPORTED before the diary is asked anything.
        DIARY_FEATURE_SCHEDULE.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListScheduleDays",
                service_name="lessons.v2.DiaryService",
                input=ListScheduleDaysRequest,
                output=ListScheduleDaysResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def list_diary_homework(
        self,
        request: ListDiaryHomeworkRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListDiaryHomeworkResponse:
        """
        A pupil's homework by due date, with corrections laid over it. Named for
        the diary because HomeworkService's ListHomework is the class's.
        DIARY_FEATURE_HOMEWORK.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDiaryHomework",
                service_name="lessons.v2.DiaryService",
                input=ListDiaryHomeworkRequest,
                output=ListDiaryHomeworkResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def list_marks(
        self,
        request: ListMarksRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListMarksResponse:
        """
        A pupil's marks, absences and lateness, which a diary files together.
        Never corrected: a family rewriting a mark would be producing a false
        record that looks official. DIARY_FEATURE_MARKS.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListMarks",
                service_name="lessons.v2.DiaryService",
                input=ListMarksRequest,
                output=ListMarksResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def list_periods(
        self,
        request: ListPeriodsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListPeriodsResponse:
        """
        A pupil's quarters or terms as the diary has them. DIARY_FEATURE_PERIODS.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPeriods",
                service_name="lessons.v2.DiaryService",
                input=ListPeriodsRequest,
                output=ListPeriodsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def list_diary_subjects(
        self,
        request: ListDiarySubjectsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListDiarySubjectsResponse:
        """
        The subjects of a period, the current one when none is named. Named for
        the diary because SubjectService's ListSubjects is the class's.
        DIARY_FEATURE_SUBJECTS.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDiarySubjects",
                service_name="lessons.v2.DiaryService",
                input=ListDiarySubjectsRequest,
                output=ListDiarySubjectsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def list_teachers(
        self,
        request: ListTeachersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListTeachersResponse:
        """
        DIARY_FEATURE_TEACHERS.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTeachers",
                service_name="lessons.v2.DiaryService",
                input=ListTeachersRequest,
                output=ListTeachersResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def list_turnstile_events(
        self,
        request: ListTurnstileEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListTurnstileEventsResponse:
        """
        Turnstile entries and exits, newest first: what v1's /attendance served.
        Absences and lateness are not here; a diary files those with the marks.
        DIARY_FEATURE_TURNSTILE.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTurnstileEvents",
                service_name="lessons.v2.DiaryService",
                input=ListTurnstileEventsRequest,
                output=ListTurnstileEventsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def list_corrections(
        self,
        request: ListCorrectionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListCorrectionsResponse:
        """
        Every correction anybody who sees this pupil made, both parents' alike;
        no row says whose. By target, then field; none for a pupil who can have
        none.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCorrections",
                service_name="lessons.v2.DiaryService",
                input=ListCorrectionsRequest,
                output=ListCorrectionsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def batch_update_corrections(
        self,
        request: BatchUpdateCorrectionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> BatchUpdateCorrectionsResponse:
        """
        Writes or replaces corrections, all or none, and answers each as it is
        stored once all are written, in the order asked. Each target is the
        string a read handed down, echoed back; the last writer wins, `original`
        included, and a target and field named twice in one request keep the
        later. At most 200 corrections a request. CORRECTIONS_UNAVAILABLE for a
        pupil who can have none. VALIDATION_FAILED, before the diary is asked
        anything: on `corrections` past 200, or naming the first correction
        refused, `corrections[i].target`, `.field` or `.value` with i counted
        from 0, for a target this server would never produce, a field that
        cannot be corrected, or an empty value where one is required.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchUpdateCorrections",
                service_name="lessons.v2.DiaryService",
                input=BatchUpdateCorrectionsRequest,
                output=BatchUpdateCorrectionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def reset_corrections(
        self,
        request: ResetCorrectionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ResetCorrectionsResponse:
        """
        Takes the named corrections off, for everyone who sees the pupil, all or
        none. It answers the same whether or not there was one, and for a pupil
        who can have none: «no correction here» is what was asked for. At most
        200 a request, as BatchUpdateCorrections. A POST with a body, because a
        target is free text, and a value that must match byte for byte does not
        travel in a URL. VALIDATION_FAILED, before the diary is asked anything:
        on `corrections` past 200 keys, or naming the first one refused,
        `corrections[i].target` or `.field` with i counted from 0, for an empty
        or overlong key.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ResetCorrections",
                service_name="lessons.v2.DiaryService",
                input=ResetCorrectionsRequest,
                output=ResetCorrectionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def clear_corrections(
        self,
        request: ClearCorrectionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ClearCorrectionsResponse:
        """
        Takes every correction for this pupil off, and nothing of any other's.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ClearCorrections",
                service_name="lessons.v2.DiaryService",
                input=ClearCorrectionsRequest,
                output=ClearCorrectionsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
