# Generated from lessons/v2/directory.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import directory_pb
from .directory_pb import ListSchoolRegionsRequest, ListSchoolRegionsResponse, ListSchoolsRequest, ListSchoolsResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class DirectoryService(Protocol):
    async def list_school_regions(self, request: ListSchoolRegionsRequest, ctx: RequestContext[ListSchoolRegionsRequest, ListSchoolRegionsResponse], /) -> ListSchoolRegionsResponse:
        """
        Which regions a school called `query` may be in, best first, at most
        ten; the order is the contract. For a phone that belongs to no class
        yet, so anonymous, and therefore metered twice:
        - twenty searches per caller in fifteen minutes (THROTTLED);
        - the anonymous share of the directory's daily allowance (DIRECTORY_SPENT).
        A query under three characters is VALIDATION_FAILED and is not counted.
        Picking the region from the list always works, so every failure says so.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_schools(self, request: ListSchoolsRequest, ctx: RequestContext[ListSchoolsRequest, ListSchoolsResponse], /) -> ListSchoolsResponse:
        """
        Schools matching `query`, looked up before UpdateClass names one, as
        «⚙️ Класс» does in the bot. An admin's, because every call spends an
        allowance somebody else pays for. Every call is one upstream search
        whatever the page, because the directory has no offset: a client asks
        once with page_size 20 and cuts the answer up itself. v1 and the design
        called it a search; as a List of schools with a query it is a standard
        method, which a method named Search on a GET is not.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in directory_pb.desc().services if s.type_name == 'lessons.v2.DirectoryService')

class DirectoryServiceASGIApplication(ConnectASGIApplication[DirectoryService]):
    def __init__(
        self,
        service: DirectoryService | AsyncGenerator[DirectoryService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/lessons.v2.DirectoryService/ListSchoolRegions": Endpoint.unary(
                    method=MethodInfo(
                        name="ListSchoolRegions",
                        service_name="lessons.v2.DirectoryService",
                        input=ListSchoolRegionsRequest,
                        output=ListSchoolRegionsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_school_regions,
                ),
                "/lessons.v2.DirectoryService/ListSchools": Endpoint.unary(
                    method=MethodInfo(
                        name="ListSchools",
                        service_name="lessons.v2.DirectoryService",
                        input=ListSchoolsRequest,
                        output=ListSchoolsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_schools,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.DirectoryService"


class DirectoryServiceClient(ConnectClient):
    async def list_school_regions(
        self,
        request: ListSchoolRegionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListSchoolRegionsResponse:
        """
        Which regions a school called `query` may be in, best first, at most
        ten; the order is the contract. For a phone that belongs to no class
        yet, so anonymous, and therefore metered twice:
        - twenty searches per caller in fifteen minutes (THROTTLED);
        - the anonymous share of the directory's daily allowance (DIRECTORY_SPENT).
        A query under three characters is VALIDATION_FAILED and is not counted.
        Picking the region from the list always works, so every failure says so.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSchoolRegions",
                service_name="lessons.v2.DirectoryService",
                input=ListSchoolRegionsRequest,
                output=ListSchoolRegionsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def list_schools(
        self,
        request: ListSchoolsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListSchoolsResponse:
        """
        Schools matching `query`, looked up before UpdateClass names one, as
        «⚙️ Класс» does in the bot. An admin's, because every call spends an
        allowance somebody else pays for. Every call is one upstream search
        whatever the page, because the directory has no offset: a client asks
        once with page_size 20 and cuts the answer up itself. v1 and the design
        called it a search; as a List of schools with a query it is a standard
        method, which a method named Search on a GET is not.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSchools",
                service_name="lessons.v2.DirectoryService",
                input=ListSchoolsRequest,
                output=ListSchoolsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

class DirectoryServiceSync(Protocol):
    def list_school_regions(self, request: ListSchoolRegionsRequest, ctx: RequestContext[ListSchoolRegionsRequest, ListSchoolRegionsResponse], /) -> ListSchoolRegionsResponse:
        """
        Which regions a school called `query` may be in, best first, at most
        ten; the order is the contract. For a phone that belongs to no class
        yet, so anonymous, and therefore metered twice:
        - twenty searches per caller in fifteen minutes (THROTTLED);
        - the anonymous share of the directory's daily allowance (DIRECTORY_SPENT).
        A query under three characters is VALIDATION_FAILED and is not counted.
        Picking the region from the list always works, so every failure says so.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_schools(self, request: ListSchoolsRequest, ctx: RequestContext[ListSchoolsRequest, ListSchoolsResponse], /) -> ListSchoolsResponse:
        """
        Schools matching `query`, looked up before UpdateClass names one, as
        «⚙️ Класс» does in the bot. An admin's, because every call spends an
        allowance somebody else pays for. Every call is one upstream search
        whatever the page, because the directory has no offset: a client asks
        once with page_size 20 and cuts the answer up itself. v1 and the design
        called it a search; as a List of schools with a query it is a standard
        method, which a method named Search on a GET is not.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in directory_pb.desc().services if s.type_name == 'lessons.v2.DirectoryService')

class DirectoryServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: DirectoryServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/lessons.v2.DirectoryService/ListSchoolRegions": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListSchoolRegions",
                        service_name="lessons.v2.DirectoryService",
                        input=ListSchoolRegionsRequest,
                        output=ListSchoolRegionsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_school_regions,
                ),
                "/lessons.v2.DirectoryService/ListSchools": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListSchools",
                        service_name="lessons.v2.DirectoryService",
                        input=ListSchoolsRequest,
                        output=ListSchoolsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_schools,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.DirectoryService"


class DirectoryServiceClientSync(ConnectClientSync):
    def list_school_regions(
        self,
        request: ListSchoolRegionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListSchoolRegionsResponse:
        """
        Which regions a school called `query` may be in, best first, at most
        ten; the order is the contract. For a phone that belongs to no class
        yet, so anonymous, and therefore metered twice:
        - twenty searches per caller in fifteen minutes (THROTTLED);
        - the anonymous share of the directory's daily allowance (DIRECTORY_SPENT).
        A query under three characters is VALIDATION_FAILED and is not counted.
        Picking the region from the list always works, so every failure says so.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSchoolRegions",
                service_name="lessons.v2.DirectoryService",
                input=ListSchoolRegionsRequest,
                output=ListSchoolRegionsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def list_schools(
        self,
        request: ListSchoolsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListSchoolsResponse:
        """
        Schools matching `query`, looked up before UpdateClass names one, as
        «⚙️ Класс» does in the bot. An admin's, because every call spends an
        allowance somebody else pays for. Every call is one upstream search
        whatever the page, because the directory has no offset: a client asks
        once with page_size 20 and cuts the answer up itself. v1 and the design
        called it a search; as a List of schools with a query it is a standard
        method, which a method named Search on a GET is not.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSchools",
                service_name="lessons.v2.DirectoryService",
                input=ListSchoolsRequest,
                output=ListSchoolsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
