# Generated from lessons/v2/errors.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.6.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import TYPE_CHECKING

from protobuf import Enum
from protobuf._codegen import file_desc

if TYPE_CHECKING:
    from protobuf import DescFile


class ErrorReason(Enum):
    """
    ```proto
    enum lessons.v2.ErrorReason
    ```

    Attributes:
        UNSPECIFIED:
            Never sent.

            ```proto
            ERROR_REASON_UNSPECIFIED = 0
            ```
        DEVICE_TOKEN_INVALID:
            UNAUTHENTICATED. No device token, or one that is unknown or revoked.
            v1: the 401 of api/deps.py («Missing bearer token», «Invalid token»).

            ```proto
            DEVICE_TOKEN_INVALID = 1
            ```
        DIARY_TOKEN_INVALID:
            UNAUTHENTICATED. No diary session token, or one that is not valid.
            v1: the 401 of api/diary.py current_diary.

            ```proto
            DIARY_TOKEN_INVALID = 2
            ```
        DEVICE_NOT_LINKED:
            PERMISSION_DENIED. The method needs a linked phone and this one is not.
            v1: 403 «device is not linked».

            ```proto
            DEVICE_NOT_LINKED = 3
            ```
        ROLE_REQUIRED:
            PERMISSION_DENIED. metadata `role`: the least role the method needs, as a
            Role value name ("ROLE_ADMIN"). v1: 403 «<role> role required».

            ```proto
            ROLE_REQUIRED = 4
            ```
        JOIN_CODE_UNKNOWN:
            NOT_FOUND. Neither a class code nor a live personal code; counted against
            the caller. v1: 404 from /join.

            ```proto
            JOIN_CODE_UNKNOWN = 5
            ```
        CLASS_INVITE_ONLY:
            PERMISSION_DENIED. A real class code for a class that takes personal codes
            only; not counted, because the caller had a real code. v1: 403 from /join.

            ```proto
            CLASS_INVITE_ONLY = 6
            ```
        DEVICE_LIMIT_REACHED:
            RESOURCE_EXHAUSTED. metadata `limit`: how many live phones the class code
            admits (#199). A personal code from the bot still works.
            v1: 409 from /join.

            ```proto
            DEVICE_LIMIT_REACHED = 7
            ```
        THROTTLED:
            RESOURCE_EXHAUSTED. metadata `retry_after_seconds`.
            v1: every 429, with Retry-After.

            ```proto
            THROTTLED = 8
            ```
        RESOURCE_NOT_FOUND:
            NOT_FOUND. metadata `resource`: "class", "subject", "bell_schedule",
            "homework", "substitution", "event", "task", "device", "access_request"
            or "student". An id from another class finds nothing, by design.
            v1: every other 404.

            ```proto
            RESOURCE_NOT_FOUND = 9
            ```
        RESOURCE_EXISTS:
            ALREADY_EXISTS. metadata `resource` and `field`: what is taken, and by
            which field ("subject" and "name", "homework" and "subject",
            "substitution" and "index"). v1: the 409 «a subject with that name is
            already in this class».

            ```proto
            RESOURCE_EXISTS = 10
            ```
        VALIDATION_FAILED:
            INVALID_ARGUMENT. A google.rpc.BadRequest in the details names each
            request field that was wrong, so a client tells them apart without the
            message. v1: every 422.

            ```proto
            VALIDATION_FAILED = 11
            ```
        NO_BELL_FOR_LESSON:
            FAILED_PRECONDITION. metadata `index`: a lesson number the day rings no
            bell for, so nothing would draw it. v1: 422 «нет звонка для урока №N в
            этот день».

            ```proto
            NO_BELL_FOR_LESSON = 12
            ```
        EMPTY_BELL_SCHEDULE:
            FAILED_PRECONDITION. A day, or the class default, pointed at a bell
            schedule with no rows. v1: 422 «в этом расписании звонков нет ни одного
            урока».

            ```proto
            EMPTY_BELL_SCHEDULE = 13
            ```
        DIARY_DISABLED:
            UNAVAILABLE. The deployment has no DIARY_SECRET, so the diary does not
            run; nothing the person types will help.
            v1: 503 with X-Diary-Unavailable: disabled.

            ```proto
            DIARY_DISABLED = 14
            ```
        DIARY_UNAVAILABLE:
            UNAVAILABLE. metadata `upstream`: "upstream" (the diary is down or will
            not take this way in: try later) or "address-refused" (the region drops
            this server's address: not the password, not worth retrying).
            v1: 503 with X-Diary-Unavailable.

            ```proto
            DIARY_UNAVAILABLE = 15
            ```
        DIARY_REAUTH:
            UNAUTHENTICATED. The diary ended the session: sign in to it again.
            v1: 401 with X-Diary-Reauth: required.

            ```proto
            DIARY_REAUTH = 16
            ```
        DIARY_CREDENTIALS_REJECTED:
            PERMISSION_DENIED. The diary would not take the session the phone opened
            from this server. Asking for the password again would loop: the session
            was good on the phone seconds ago. v1: 409 from /diary/session.

            ```proto
            DIARY_CREDENTIALS_REJECTED = 17
            ```
        DIRECTORY_DISABLED:
            UNAVAILABLE. The deployment has no DADATA_TOKEN: pick the region from the
            list, or type the school. v1: 503 with X-Directory-Unavailable: disabled.

            ```proto
            DIRECTORY_DISABLED = 18
            ```
        DIRECTORY_SPENT:
            RESOURCE_EXHAUSTED. metadata `retry_after_seconds`, until the next Moscow
            day: today's anonymous share of the directory is spent.
            v1: 503 with X-Directory-Unavailable: spent, and Retry-After.

            ```proto
            DIRECTORY_SPENT = 19
            ```
        DIRECTORY_UNAVAILABLE:
            UNAVAILABLE. The directory failed.
            v1: 503 with X-Directory-Unavailable: upstream.

            ```proto
            DIRECTORY_UNAVAILABLE = 20
            ```
        CLIENT_TOO_OLD:
            FAILED_PRECONDITION. metadata `min_version`: the oldest client version
            code the server still serves; the app says «обновите приложение».
            New in v2.

            ```proto
            CLIENT_TOO_OLD = 21
            ```
        FEATURE_UNSUPPORTED:
            UNIMPLEMENTED. metadata `feature`: a DiaryFeature value name, or a server
            capability, that this server or this diary does not have. New in v2.

            ```proto
            FEATURE_UNSUPPORTED = 22
            ```
        REQUEST_UNDECODABLE:
            INVALID_ARGUMENT. The request could not be decoded at all: bad JSON, a
            bad varint, a string where a number belongs. New in v2: the spike's 500.

            ```proto
            REQUEST_UNDECODABLE = 23
            ```
        DIARY_NO_STUDENTS:
            PERMISSION_DENIED. The diary account lists no pupil, so there is nothing
            to read. v1: 403 from /diary/session (api/diary.py, NoStudents).

            ```proto
            DIARY_NO_STUDENTS = 24
            ```
        DIARY_UPSTREAM_UNREADABLE:
            UNAVAILABLE. The diary answered something nobody can read, often a login
            page where data belongs. v1: 502 (api/diary.py, UnexpectedResponse and
            DiaryError, in _guard and in register_session).

            ```proto
            DIARY_UPSTREAM_UNREADABLE = 25
            ```
        CORRECTIONS_UNAVAILABLE:
            FAILED_PRECONDITION. This pupil can have no corrections: the diary lists
            them outside its own numbering. v1: 422 «Для этого ученика правки
            недоступны» (api/diary.py, put_override).

            ```proto
            CORRECTIONS_UNAVAILABLE = 26
            ```
        RESOURCE_IN_USE:
            FAILED_PRECONDITION. metadata `resource`, `used_by` and, where there is
            one, `count`: a subject the weekly template still teaches ("lessons"), a
            bell schedule special days point at ("days"), or the class default
            ("class"). v1: 409 from DELETE /manage/subjects/{id} (SubjectInUse) and
            DELETE /manage/bells/{id} (ScheduleIsDefault, ScheduleInUse).

            ```proto
            RESOURCE_IN_USE = 27
            ```
        SUBJECT_RENAME_CLASH:
            FAILED_PRECONDITION. metadata `dates`: comma-separated "YYYY-MM-DD", the
            days on which both names have homework, which a rename would merge.
            v1: 409 «homework under both names on the same day» (HomeworkClash).

            ```proto
            SUBJECT_RENAME_CLASH = 28
            ```
        CLASS_DEVICE_NOT_LINKED:
            FAILED_PRECONDITION. The device an admin asked to unlink is not linked.
            v1: 409 from POST /manage/devices/{id}/unlink (DeviceNotLinked).

            ```proto
            CLASS_DEVICE_NOT_LINKED = 29
            ```
        ROLE_GRANT_REFUSED:
            PERMISSION_DENIED. metadata `why`: "role_too_high" (nobody grants at or
            above their own role) or "member_senior" (the member is the admin's peer
            or senior). v1: 403 from POST /manage/requests/{id}/approve (GrantRefused).

            ```proto
            ROLE_GRANT_REFUSED = 30
            ```
        TERM_BOUNDS_REFUSED:
            FAILED_PRECONDITION. A term's dates the school year cannot hold: past
            31 May, overlapping a neighbour, ending before they start; or a term the
            year does not have («Такого периода нет.»). The message is the service's
            own Russian sentence. v1: 422 from PUT /manage/terms/{index} (TermError).

            ```proto
            TERM_BOUNDS_REFUSED = 31
            ```
        NO_LESSON_ON_DAY:
            FAILED_PRECONDITION. metadata `why`: "out_of_year", "between_terms",
            "public_holiday" or "marked_day_off". The day draws no lessons at all, so
            a substitution on it would be announced and drawn nowhere. v1: 422 from
            PUT /overrides (timetable_edit.why_no_lesson_can_be_drawn).

            ```proto
            NO_LESSON_ON_DAY = 32
            ```
        LESSON_NOT_ON_TIMETABLE:
            FAILED_PRECONDITION. metadata `index`: cancelling, or substituting without
            a subject, a lesson number the day's template does not have.
            v1: 422 «в этот день нет урока №N…» from PUT /overrides.

            ```proto
            LESSON_NOT_ON_TIMETABLE = 33
            ```
    """

    UNSPECIFIED = 0
    DEVICE_TOKEN_INVALID = 1
    DIARY_TOKEN_INVALID = 2
    DEVICE_NOT_LINKED = 3
    ROLE_REQUIRED = 4
    JOIN_CODE_UNKNOWN = 5
    CLASS_INVITE_ONLY = 6
    DEVICE_LIMIT_REACHED = 7
    THROTTLED = 8
    RESOURCE_NOT_FOUND = 9
    RESOURCE_EXISTS = 10
    VALIDATION_FAILED = 11
    NO_BELL_FOR_LESSON = 12
    EMPTY_BELL_SCHEDULE = 13
    DIARY_DISABLED = 14
    DIARY_UNAVAILABLE = 15
    DIARY_REAUTH = 16
    DIARY_CREDENTIALS_REJECTED = 17
    DIRECTORY_DISABLED = 18
    DIRECTORY_SPENT = 19
    DIRECTORY_UNAVAILABLE = 20
    CLIENT_TOO_OLD = 21
    FEATURE_UNSUPPORTED = 22
    REQUEST_UNDECODABLE = 23
    DIARY_NO_STUDENTS = 24
    DIARY_UPSTREAM_UNREADABLE = 25
    CORRECTIONS_UNAVAILABLE = 26
    RESOURCE_IN_USE = 27
    SUBJECT_RENAME_CLASH = 28
    CLASS_DEVICE_NOT_LINKED = 29
    ROLE_GRANT_REFUSED = 30
    TERM_BOUNDS_REFUSED = 31
    NO_LESSON_ON_DAY = 32
    LESSON_NOT_ON_TIMETABLE = 33


_DESC = file_desc(
    b'\n\x17lessons/v2/errors.proto\x12\nlessons.v2*\xc2\x06\n\x0bErrorReason\x12\x1c\n\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x18\n\x14DEVICE_TOKEN_INVALID\x10\x01\x12\x17\n\x13DIARY_TOKEN_INVALID\x10\x02\x12\x15\n\x11DEVICE_NOT_LINKED\x10\x03\x12\x11\n\rROLE_REQUIRED\x10\x04\x12\x15\n\x11JOIN_CODE_UNKNOWN\x10\x05\x12\x15\n\x11CLASS_INVITE_ONLY\x10\x06\x12\x18\n\x14DEVICE_LIMIT_REACHED\x10\x07\x12\r\n\tTHROTTLED\x10\x08\x12\x16\n\x12RESOURCE_NOT_FOUND\x10\t\x12\x13\n\x0fRESOURCE_EXISTS\x10\n\x12\x15\n\x11VALIDATION_FAILED\x10\x0b\x12\x16\n\x12NO_BELL_FOR_LESSON\x10\x0c\x12\x17\n\x13EMPTY_BELL_SCHEDULE\x10\r\x12\x12\n\x0eDIARY_DISABLED\x10\x0e\x12\x15\n\x11DIARY_UNAVAILABLE\x10\x0f\x12\x10\n\x0cDIARY_REAUTH\x10\x10\x12\x1e\n\x1aDIARY_CREDENTIALS_REJECTED\x10\x11\x12\x16\n\x12DIRECTORY_DISABLED\x10\x12\x12\x13\n\x0fDIRECTORY_SPENT\x10\x13\x12\x19\n\x15DIRECTORY_UNAVAILABLE\x10\x14\x12\x12\n\x0eCLIENT_TOO_OLD\x10\x15\x12\x17\n\x13FEATURE_UNSUPPORTED\x10\x16\x12\x17\n\x13REQUEST_UNDECODABLE\x10\x17\x12\x15\n\x11DIARY_NO_STUDENTS\x10\x18\x12\x1d\n\x19DIARY_UPSTREAM_UNREADABLE\x10\x19\x12\x1b\n\x17CORRECTIONS_UNAVAILABLE\x10\x1a\x12\x13\n\x0fRESOURCE_IN_USE\x10\x1b\x12\x18\n\x14SUBJECT_RENAME_CLASH\x10\x1c\x12\x1b\n\x17CLASS_DEVICE_NOT_LINKED\x10\x1d\x12\x16\n\x12ROLE_GRANT_REFUSED\x10\x1e\x12\x17\n\x13TERM_BOUNDS_REFUSED\x10\x1f\x12\x14\n\x10NO_LESSON_ON_DAY\x10 \x12\x1b\n\x17LESSON_NOT_ON_TIMETABLE\x10!B(\n$com.lumenpearson.lessons.contract.v2P\x01b\x06proto3',
    [],
    {
        "ErrorReason": ErrorReason,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `lessons/v2/errors.proto`."""
    return _DESC
