# Generated from lessons/v2/event.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import event_pb
from .event_pb import CreateEventRequest, CreateEventResponse, DeleteEventRequest, DeleteEventResponse, GetEventRequest, GetEventResponse, ListEventsRequest, ListEventsResponse, UpdateEventRequest, UpdateEventResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class EventService(Protocol):
    async def list_events(self, request: ListEventsRequest, ctx: RequestContext[ListEventsRequest, ListEventsResponse], /) -> ListEventsResponse:
        """
        Events on dates in a window: today and 21 days on when unset, 62 days at
        most.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_event(self, request: GetEventRequest, ctx: RequestContext[GetEventRequest, GetEventResponse], /) -> GetEventResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def create_event(self, request: CreateEventRequest, ctx: RequestContext[CreateEventRequest, CreateEventResponse], /) -> CreateEventResponse:
        """
        A POST, so a retried create can be told apart from a second event. Events
        have no natural key: two «Обед» on one day are two breaks. Announced to
        the class's subscribers. REST answers 201.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def update_event(self, request: UpdateEventRequest, ctx: RequestContext[UpdateEventRequest, UpdateEventResponse], /) -> UpdateEventResponse:
        """
        `update_mask` takes date, starts_at, ends_at, title, kind, location and
        covers_lesson. A path whose field is absent clears it: location goes,
        covers_lesson goes back to what the kind means, and kind becomes
        EVENT_KIND_EVENT; date, starts_at, ends_at and title cannot be cleared. A
        time that moves is held against the one that stays. Announced to the
        class's subscribers once, on the date it is on afterwards, unless nothing
        changed.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_event(self, request: DeleteEventRequest, ctx: RequestContext[DeleteEventRequest, DeleteEventResponse], /) -> DeleteEventResponse:
        """
        Announced to the class's subscribers.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in event_pb.desc().services if s.type_name == 'lessons.v2.EventService')

class EventServiceASGIApplication(ConnectASGIApplication[EventService]):
    def __init__(
        self,
        service: EventService | AsyncGenerator[EventService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/lessons.v2.EventService/ListEvents": Endpoint.unary(
                    method=MethodInfo(
                        name="ListEvents",
                        service_name="lessons.v2.EventService",
                        input=ListEventsRequest,
                        output=ListEventsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_events,
                ),
                "/lessons.v2.EventService/GetEvent": Endpoint.unary(
                    method=MethodInfo(
                        name="GetEvent",
                        service_name="lessons.v2.EventService",
                        input=GetEventRequest,
                        output=GetEventResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_event,
                ),
                "/lessons.v2.EventService/CreateEvent": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateEvent",
                        service_name="lessons.v2.EventService",
                        input=CreateEventRequest,
                        output=CreateEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_event,
                ),
                "/lessons.v2.EventService/UpdateEvent": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateEvent",
                        service_name="lessons.v2.EventService",
                        input=UpdateEventRequest,
                        output=UpdateEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_event,
                ),
                "/lessons.v2.EventService/DeleteEvent": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteEvent",
                        service_name="lessons.v2.EventService",
                        input=DeleteEventRequest,
                        output=DeleteEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_event,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.EventService"


class EventServiceClient(ConnectClient):
    async def list_events(
        self,
        request: ListEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListEventsResponse:
        """
        Events on dates in a window: today and 21 days on when unset, 62 days at
        most.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListEvents",
                service_name="lessons.v2.EventService",
                input=ListEventsRequest,
                output=ListEventsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_event(
        self,
        request: GetEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetEventResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetEvent",
                service_name="lessons.v2.EventService",
                input=GetEventRequest,
                output=GetEventResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_event(
        self,
        request: CreateEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateEventResponse:
        """
        A POST, so a retried create can be told apart from a second event. Events
        have no natural key: two «Обед» on one day are two breaks. Announced to
        the class's subscribers. REST answers 201.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateEvent",
                service_name="lessons.v2.EventService",
                input=CreateEventRequest,
                output=CreateEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_event(
        self,
        request: UpdateEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdateEventResponse:
        """
        `update_mask` takes date, starts_at, ends_at, title, kind, location and
        covers_lesson. A path whose field is absent clears it: location goes,
        covers_lesson goes back to what the kind means, and kind becomes
        EVENT_KIND_EVENT; date, starts_at, ends_at and title cannot be cleared. A
        time that moves is held against the one that stays. Announced to the
        class's subscribers once, on the date it is on afterwards, unless nothing
        changed.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateEvent",
                service_name="lessons.v2.EventService",
                input=UpdateEventRequest,
                output=UpdateEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_event(
        self,
        request: DeleteEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteEventResponse:
        """
        Announced to the class's subscribers.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteEvent",
                service_name="lessons.v2.EventService",
                input=DeleteEventRequest,
                output=DeleteEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class EventServiceSync(Protocol):
    def list_events(self, request: ListEventsRequest, ctx: RequestContext[ListEventsRequest, ListEventsResponse], /) -> ListEventsResponse:
        """
        Events on dates in a window: today and 21 days on when unset, 62 days at
        most.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_event(self, request: GetEventRequest, ctx: RequestContext[GetEventRequest, GetEventResponse], /) -> GetEventResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def create_event(self, request: CreateEventRequest, ctx: RequestContext[CreateEventRequest, CreateEventResponse], /) -> CreateEventResponse:
        """
        A POST, so a retried create can be told apart from a second event. Events
        have no natural key: two «Обед» on one day are two breaks. Announced to
        the class's subscribers. REST answers 201.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def update_event(self, request: UpdateEventRequest, ctx: RequestContext[UpdateEventRequest, UpdateEventResponse], /) -> UpdateEventResponse:
        """
        `update_mask` takes date, starts_at, ends_at, title, kind, location and
        covers_lesson. A path whose field is absent clears it: location goes,
        covers_lesson goes back to what the kind means, and kind becomes
        EVENT_KIND_EVENT; date, starts_at, ends_at and title cannot be cleared. A
        time that moves is held against the one that stays. Announced to the
        class's subscribers once, on the date it is on afterwards, unless nothing
        changed.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_event(self, request: DeleteEventRequest, ctx: RequestContext[DeleteEventRequest, DeleteEventResponse], /) -> DeleteEventResponse:
        """
        Announced to the class's subscribers.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in event_pb.desc().services if s.type_name == 'lessons.v2.EventService')

class EventServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: EventServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/lessons.v2.EventService/ListEvents": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListEvents",
                        service_name="lessons.v2.EventService",
                        input=ListEventsRequest,
                        output=ListEventsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_events,
                ),
                "/lessons.v2.EventService/GetEvent": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetEvent",
                        service_name="lessons.v2.EventService",
                        input=GetEventRequest,
                        output=GetEventResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_event,
                ),
                "/lessons.v2.EventService/CreateEvent": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateEvent",
                        service_name="lessons.v2.EventService",
                        input=CreateEventRequest,
                        output=CreateEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_event,
                ),
                "/lessons.v2.EventService/UpdateEvent": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateEvent",
                        service_name="lessons.v2.EventService",
                        input=UpdateEventRequest,
                        output=UpdateEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_event,
                ),
                "/lessons.v2.EventService/DeleteEvent": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteEvent",
                        service_name="lessons.v2.EventService",
                        input=DeleteEventRequest,
                        output=DeleteEventResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_event,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.EventService"


class EventServiceClientSync(ConnectClientSync):
    def list_events(
        self,
        request: ListEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListEventsResponse:
        """
        Events on dates in a window: today and 21 days on when unset, 62 days at
        most.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListEvents",
                service_name="lessons.v2.EventService",
                input=ListEventsRequest,
                output=ListEventsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def get_event(
        self,
        request: GetEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetEventResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetEvent",
                service_name="lessons.v2.EventService",
                input=GetEventRequest,
                output=GetEventResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def create_event(
        self,
        request: CreateEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateEventResponse:
        """
        A POST, so a retried create can be told apart from a second event. Events
        have no natural key: two «Обед» on one day are two breaks. Announced to
        the class's subscribers. REST answers 201.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateEvent",
                service_name="lessons.v2.EventService",
                input=CreateEventRequest,
                output=CreateEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def update_event(
        self,
        request: UpdateEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdateEventResponse:
        """
        `update_mask` takes date, starts_at, ends_at, title, kind, location and
        covers_lesson. A path whose field is absent clears it: location goes,
        covers_lesson goes back to what the kind means, and kind becomes
        EVENT_KIND_EVENT; date, starts_at, ends_at and title cannot be cleared. A
        time that moves is held against the one that stays. Announced to the
        class's subscribers once, on the date it is on afterwards, unless nothing
        changed.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateEvent",
                service_name="lessons.v2.EventService",
                input=UpdateEventRequest,
                output=UpdateEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_event(
        self,
        request: DeleteEventRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteEventResponse:
        """
        Announced to the class's subscribers.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteEvent",
                service_name="lessons.v2.EventService",
                input=DeleteEventRequest,
                output=DeleteEventResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
