# Generated from lessons/v2/me.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import me_pb
from .me_pb import CreateCalendarFeedRequest, CreateCalendarFeedResponse, CreateHomeworkTickRequest, CreateHomeworkTickResponse, CreateLinkCodeRequest, CreateLinkCodeResponse, CreateTaskRequest, CreateTaskResponse, DeleteHomeworkTickRequest, DeleteHomeworkTickResponse, DeleteTaskRequest, DeleteTaskResponse, GetCalendarFeedRequest, GetCalendarFeedResponse, GetMeRequest, GetMeResponse, GetTaskRequest, GetTaskResponse, ListTasksRequest, ListTasksResponse, UnlinkMeRequest, UnlinkMeResponse, UpdateTaskRequest, UpdateTaskResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class MeService(Protocol):
    async def get_me(self, request: GetMeRequest, ctx: RequestContext[GetMeRequest, GetMeResponse], /) -> GetMeResponse:
        """
        Who this device is. Mints nothing: v1's GET /me issued a link code as a
        side effect, which CreateLinkCode does now.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def unlink_me(self, request: UnlinkMeRequest, ctx: RequestContext[UnlinkMeRequest, UnlinkMeResponse], /) -> UnlinkMeResponse:
        """
        Back to read-only, keeping the phone in the class. Unlinking a phone that
        is not linked is not an error.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def create_link_code(self, request: CreateLinkCodeRequest, ctx: RequestContext[CreateLinkCodeRequest, CreateLinkCodeResponse], /) -> CreateLinkCodeResponse:
        """
        A code that links this phone to the Telegram account that sends it to the
        bot. A phone already linked gets none: a code left on a linked row could
        be typed by somebody else and re-home the phone.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_calendar_feed(self, request: GetCalendarFeedRequest, ctx: RequestContext[GetCalendarFeedRequest, GetCalendarFeedResponse], /) -> GetCalendarFeedResponse:
        """
        The class's calendar subscription, when the class has a feed secret.
        Never mints one.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def create_calendar_feed(self, request: CreateCalendarFeedRequest, ctx: RequestContext[CreateCalendarFeedRequest, CreateCalendarFeedResponse], /) -> CreateCalendarFeedResponse:
        """
        Mints the class's feed when it has none, and answers the existing feed
        when it has one. v2 has no rotation: the feed is the whole class's, and a
        new secret would cut off every calendar subscribed to the old one.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_tasks(self, request: ListTasksRequest, ctx: RequestContext[ListTasksRequest, ListTasksResponse], /) -> ListTasksResponse:
        """
        The linked account's tasks in this class, at most 200; done ones only
        when asked for.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_task(self, request: GetTaskRequest, ctx: RequestContext[GetTaskRequest, GetTaskResponse], /) -> GetTaskResponse:
        """
        RESOURCE_NOT_FOUND for somebody else's task as for one that never
        existed: an id must not reveal that a classmate keeps a list.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def create_task(self, request: CreateTaskRequest, ctx: RequestContext[CreateTaskRequest, CreateTaskResponse], /) -> CreateTaskResponse:
        """
        `homework_id`, when set, names homework of this class (VALIDATION_FAILED
        otherwise). REST answers 201.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def update_task(self, request: UpdateTaskRequest, ctx: RequestContext[UpdateTaskRequest, UpdateTaskResponse], /) -> UpdateTaskResponse:
        """
        `update_mask` takes title, notes, subject_name, due_date, due_time,
        priority, homework_id, remind_at and done; v1's POST /tasks/{id}/done is
        this with `done`. A path whose field is absent clears it, except title
        and priority, which cannot be cleared.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_task(self, request: DeleteTaskRequest, ctx: RequestContext[DeleteTaskRequest, DeleteTaskResponse], /) -> DeleteTaskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def create_homework_tick(self, request: CreateHomeworkTickRequest, ctx: RequestContext[CreateHomeworkTickRequest, CreateHomeworkTickResponse], /) -> CreateHomeworkTickResponse:
        """
        Ticks homework off for the linked account. Ticking it twice is not an
        error: the app sends the state it shows, so a retry lands on the same
        answer.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_homework_tick(self, request: DeleteHomeworkTickRequest, ctx: RequestContext[DeleteHomeworkTickRequest, DeleteHomeworkTickResponse], /) -> DeleteHomeworkTickResponse:
        """
        Takes the tick off; taking off one that is not there is not an error.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in me_pb.desc().services if s.type_name == 'lessons.v2.MeService')

class MeServiceASGIApplication(ConnectASGIApplication[MeService]):
    def __init__(
        self,
        service: MeService | AsyncGenerator[MeService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/lessons.v2.MeService/GetMe": Endpoint.unary(
                    method=MethodInfo(
                        name="GetMe",
                        service_name="lessons.v2.MeService",
                        input=GetMeRequest,
                        output=GetMeResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_me,
                ),
                "/lessons.v2.MeService/UnlinkMe": Endpoint.unary(
                    method=MethodInfo(
                        name="UnlinkMe",
                        service_name="lessons.v2.MeService",
                        input=UnlinkMeRequest,
                        output=UnlinkMeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.unlink_me,
                ),
                "/lessons.v2.MeService/CreateLinkCode": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateLinkCode",
                        service_name="lessons.v2.MeService",
                        input=CreateLinkCodeRequest,
                        output=CreateLinkCodeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_link_code,
                ),
                "/lessons.v2.MeService/GetCalendarFeed": Endpoint.unary(
                    method=MethodInfo(
                        name="GetCalendarFeed",
                        service_name="lessons.v2.MeService",
                        input=GetCalendarFeedRequest,
                        output=GetCalendarFeedResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_calendar_feed,
                ),
                "/lessons.v2.MeService/CreateCalendarFeed": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateCalendarFeed",
                        service_name="lessons.v2.MeService",
                        input=CreateCalendarFeedRequest,
                        output=CreateCalendarFeedResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_calendar_feed,
                ),
                "/lessons.v2.MeService/ListTasks": Endpoint.unary(
                    method=MethodInfo(
                        name="ListTasks",
                        service_name="lessons.v2.MeService",
                        input=ListTasksRequest,
                        output=ListTasksResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_tasks,
                ),
                "/lessons.v2.MeService/GetTask": Endpoint.unary(
                    method=MethodInfo(
                        name="GetTask",
                        service_name="lessons.v2.MeService",
                        input=GetTaskRequest,
                        output=GetTaskResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_task,
                ),
                "/lessons.v2.MeService/CreateTask": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateTask",
                        service_name="lessons.v2.MeService",
                        input=CreateTaskRequest,
                        output=CreateTaskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_task,
                ),
                "/lessons.v2.MeService/UpdateTask": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateTask",
                        service_name="lessons.v2.MeService",
                        input=UpdateTaskRequest,
                        output=UpdateTaskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_task,
                ),
                "/lessons.v2.MeService/DeleteTask": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteTask",
                        service_name="lessons.v2.MeService",
                        input=DeleteTaskRequest,
                        output=DeleteTaskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_task,
                ),
                "/lessons.v2.MeService/CreateHomeworkTick": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateHomeworkTick",
                        service_name="lessons.v2.MeService",
                        input=CreateHomeworkTickRequest,
                        output=CreateHomeworkTickResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_homework_tick,
                ),
                "/lessons.v2.MeService/DeleteHomeworkTick": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteHomeworkTick",
                        service_name="lessons.v2.MeService",
                        input=DeleteHomeworkTickRequest,
                        output=DeleteHomeworkTickResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_homework_tick,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.MeService"


class MeServiceClient(ConnectClient):
    async def get_me(
        self,
        request: GetMeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetMeResponse:
        """
        Who this device is. Mints nothing: v1's GET /me issued a link code as a
        side effect, which CreateLinkCode does now.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetMe",
                service_name="lessons.v2.MeService",
                input=GetMeRequest,
                output=GetMeResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def unlink_me(
        self,
        request: UnlinkMeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UnlinkMeResponse:
        """
        Back to read-only, keeping the phone in the class. Unlinking a phone that
        is not linked is not an error.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnlinkMe",
                service_name="lessons.v2.MeService",
                input=UnlinkMeRequest,
                output=UnlinkMeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_link_code(
        self,
        request: CreateLinkCodeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateLinkCodeResponse:
        """
        A code that links this phone to the Telegram account that sends it to the
        bot. A phone already linked gets none: a code left on a linked row could
        be typed by somebody else and re-home the phone.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateLinkCode",
                service_name="lessons.v2.MeService",
                input=CreateLinkCodeRequest,
                output=CreateLinkCodeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_calendar_feed(
        self,
        request: GetCalendarFeedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetCalendarFeedResponse:
        """
        The class's calendar subscription, when the class has a feed secret.
        Never mints one.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCalendarFeed",
                service_name="lessons.v2.MeService",
                input=GetCalendarFeedRequest,
                output=GetCalendarFeedResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_calendar_feed(
        self,
        request: CreateCalendarFeedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateCalendarFeedResponse:
        """
        Mints the class's feed when it has none, and answers the existing feed
        when it has one. v2 has no rotation: the feed is the whole class's, and a
        new secret would cut off every calendar subscribed to the old one.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateCalendarFeed",
                service_name="lessons.v2.MeService",
                input=CreateCalendarFeedRequest,
                output=CreateCalendarFeedResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_tasks(
        self,
        request: ListTasksRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListTasksResponse:
        """
        The linked account's tasks in this class, at most 200; done ones only
        when asked for.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTasks",
                service_name="lessons.v2.MeService",
                input=ListTasksRequest,
                output=ListTasksResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_task(
        self,
        request: GetTaskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetTaskResponse:
        """
        RESOURCE_NOT_FOUND for somebody else's task as for one that never
        existed: an id must not reveal that a classmate keeps a list.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTask",
                service_name="lessons.v2.MeService",
                input=GetTaskRequest,
                output=GetTaskResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_task(
        self,
        request: CreateTaskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateTaskResponse:
        """
        `homework_id`, when set, names homework of this class (VALIDATION_FAILED
        otherwise). REST answers 201.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateTask",
                service_name="lessons.v2.MeService",
                input=CreateTaskRequest,
                output=CreateTaskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_task(
        self,
        request: UpdateTaskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdateTaskResponse:
        """
        `update_mask` takes title, notes, subject_name, due_date, due_time,
        priority, homework_id, remind_at and done; v1's POST /tasks/{id}/done is
        this with `done`. A path whose field is absent clears it, except title
        and priority, which cannot be cleared.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateTask",
                service_name="lessons.v2.MeService",
                input=UpdateTaskRequest,
                output=UpdateTaskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_task(
        self,
        request: DeleteTaskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteTaskResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteTask",
                service_name="lessons.v2.MeService",
                input=DeleteTaskRequest,
                output=DeleteTaskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_homework_tick(
        self,
        request: CreateHomeworkTickRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateHomeworkTickResponse:
        """
        Ticks homework off for the linked account. Ticking it twice is not an
        error: the app sends the state it shows, so a retry lands on the same
        answer.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateHomeworkTick",
                service_name="lessons.v2.MeService",
                input=CreateHomeworkTickRequest,
                output=CreateHomeworkTickResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_homework_tick(
        self,
        request: DeleteHomeworkTickRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteHomeworkTickResponse:
        """
        Takes the tick off; taking off one that is not there is not an error.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteHomeworkTick",
                service_name="lessons.v2.MeService",
                input=DeleteHomeworkTickRequest,
                output=DeleteHomeworkTickResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class MeServiceSync(Protocol):
    def get_me(self, request: GetMeRequest, ctx: RequestContext[GetMeRequest, GetMeResponse], /) -> GetMeResponse:
        """
        Who this device is. Mints nothing: v1's GET /me issued a link code as a
        side effect, which CreateLinkCode does now.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def unlink_me(self, request: UnlinkMeRequest, ctx: RequestContext[UnlinkMeRequest, UnlinkMeResponse], /) -> UnlinkMeResponse:
        """
        Back to read-only, keeping the phone in the class. Unlinking a phone that
        is not linked is not an error.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def create_link_code(self, request: CreateLinkCodeRequest, ctx: RequestContext[CreateLinkCodeRequest, CreateLinkCodeResponse], /) -> CreateLinkCodeResponse:
        """
        A code that links this phone to the Telegram account that sends it to the
        bot. A phone already linked gets none: a code left on a linked row could
        be typed by somebody else and re-home the phone.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_calendar_feed(self, request: GetCalendarFeedRequest, ctx: RequestContext[GetCalendarFeedRequest, GetCalendarFeedResponse], /) -> GetCalendarFeedResponse:
        """
        The class's calendar subscription, when the class has a feed secret.
        Never mints one.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def create_calendar_feed(self, request: CreateCalendarFeedRequest, ctx: RequestContext[CreateCalendarFeedRequest, CreateCalendarFeedResponse], /) -> CreateCalendarFeedResponse:
        """
        Mints the class's feed when it has none, and answers the existing feed
        when it has one. v2 has no rotation: the feed is the whole class's, and a
        new secret would cut off every calendar subscribed to the old one.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_tasks(self, request: ListTasksRequest, ctx: RequestContext[ListTasksRequest, ListTasksResponse], /) -> ListTasksResponse:
        """
        The linked account's tasks in this class, at most 200; done ones only
        when asked for.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_task(self, request: GetTaskRequest, ctx: RequestContext[GetTaskRequest, GetTaskResponse], /) -> GetTaskResponse:
        """
        RESOURCE_NOT_FOUND for somebody else's task as for one that never
        existed: an id must not reveal that a classmate keeps a list.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def create_task(self, request: CreateTaskRequest, ctx: RequestContext[CreateTaskRequest, CreateTaskResponse], /) -> CreateTaskResponse:
        """
        `homework_id`, when set, names homework of this class (VALIDATION_FAILED
        otherwise). REST answers 201.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def update_task(self, request: UpdateTaskRequest, ctx: RequestContext[UpdateTaskRequest, UpdateTaskResponse], /) -> UpdateTaskResponse:
        """
        `update_mask` takes title, notes, subject_name, due_date, due_time,
        priority, homework_id, remind_at and done; v1's POST /tasks/{id}/done is
        this with `done`. A path whose field is absent clears it, except title
        and priority, which cannot be cleared.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_task(self, request: DeleteTaskRequest, ctx: RequestContext[DeleteTaskRequest, DeleteTaskResponse], /) -> DeleteTaskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def create_homework_tick(self, request: CreateHomeworkTickRequest, ctx: RequestContext[CreateHomeworkTickRequest, CreateHomeworkTickResponse], /) -> CreateHomeworkTickResponse:
        """
        Ticks homework off for the linked account. Ticking it twice is not an
        error: the app sends the state it shows, so a retry lands on the same
        answer.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_homework_tick(self, request: DeleteHomeworkTickRequest, ctx: RequestContext[DeleteHomeworkTickRequest, DeleteHomeworkTickResponse], /) -> DeleteHomeworkTickResponse:
        """
        Takes the tick off; taking off one that is not there is not an error.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in me_pb.desc().services if s.type_name == 'lessons.v2.MeService')

class MeServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: MeServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/lessons.v2.MeService/GetMe": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetMe",
                        service_name="lessons.v2.MeService",
                        input=GetMeRequest,
                        output=GetMeResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_me,
                ),
                "/lessons.v2.MeService/UnlinkMe": EndpointSync.unary(
                    method=MethodInfo(
                        name="UnlinkMe",
                        service_name="lessons.v2.MeService",
                        input=UnlinkMeRequest,
                        output=UnlinkMeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.unlink_me,
                ),
                "/lessons.v2.MeService/CreateLinkCode": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateLinkCode",
                        service_name="lessons.v2.MeService",
                        input=CreateLinkCodeRequest,
                        output=CreateLinkCodeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_link_code,
                ),
                "/lessons.v2.MeService/GetCalendarFeed": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetCalendarFeed",
                        service_name="lessons.v2.MeService",
                        input=GetCalendarFeedRequest,
                        output=GetCalendarFeedResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_calendar_feed,
                ),
                "/lessons.v2.MeService/CreateCalendarFeed": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateCalendarFeed",
                        service_name="lessons.v2.MeService",
                        input=CreateCalendarFeedRequest,
                        output=CreateCalendarFeedResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_calendar_feed,
                ),
                "/lessons.v2.MeService/ListTasks": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListTasks",
                        service_name="lessons.v2.MeService",
                        input=ListTasksRequest,
                        output=ListTasksResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_tasks,
                ),
                "/lessons.v2.MeService/GetTask": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetTask",
                        service_name="lessons.v2.MeService",
                        input=GetTaskRequest,
                        output=GetTaskResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_task,
                ),
                "/lessons.v2.MeService/CreateTask": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateTask",
                        service_name="lessons.v2.MeService",
                        input=CreateTaskRequest,
                        output=CreateTaskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_task,
                ),
                "/lessons.v2.MeService/UpdateTask": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateTask",
                        service_name="lessons.v2.MeService",
                        input=UpdateTaskRequest,
                        output=UpdateTaskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_task,
                ),
                "/lessons.v2.MeService/DeleteTask": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteTask",
                        service_name="lessons.v2.MeService",
                        input=DeleteTaskRequest,
                        output=DeleteTaskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_task,
                ),
                "/lessons.v2.MeService/CreateHomeworkTick": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateHomeworkTick",
                        service_name="lessons.v2.MeService",
                        input=CreateHomeworkTickRequest,
                        output=CreateHomeworkTickResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_homework_tick,
                ),
                "/lessons.v2.MeService/DeleteHomeworkTick": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteHomeworkTick",
                        service_name="lessons.v2.MeService",
                        input=DeleteHomeworkTickRequest,
                        output=DeleteHomeworkTickResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_homework_tick,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.MeService"


class MeServiceClientSync(ConnectClientSync):
    def get_me(
        self,
        request: GetMeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetMeResponse:
        """
        Who this device is. Mints nothing: v1's GET /me issued a link code as a
        side effect, which CreateLinkCode does now.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetMe",
                service_name="lessons.v2.MeService",
                input=GetMeRequest,
                output=GetMeResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def unlink_me(
        self,
        request: UnlinkMeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UnlinkMeResponse:
        """
        Back to read-only, keeping the phone in the class. Unlinking a phone that
        is not linked is not an error.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnlinkMe",
                service_name="lessons.v2.MeService",
                input=UnlinkMeRequest,
                output=UnlinkMeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def create_link_code(
        self,
        request: CreateLinkCodeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateLinkCodeResponse:
        """
        A code that links this phone to the Telegram account that sends it to the
        bot. A phone already linked gets none: a code left on a linked row could
        be typed by somebody else and re-home the phone.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateLinkCode",
                service_name="lessons.v2.MeService",
                input=CreateLinkCodeRequest,
                output=CreateLinkCodeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_calendar_feed(
        self,
        request: GetCalendarFeedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetCalendarFeedResponse:
        """
        The class's calendar subscription, when the class has a feed secret.
        Never mints one.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCalendarFeed",
                service_name="lessons.v2.MeService",
                input=GetCalendarFeedRequest,
                output=GetCalendarFeedResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def create_calendar_feed(
        self,
        request: CreateCalendarFeedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateCalendarFeedResponse:
        """
        Mints the class's feed when it has none, and answers the existing feed
        when it has one. v2 has no rotation: the feed is the whole class's, and a
        new secret would cut off every calendar subscribed to the old one.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateCalendarFeed",
                service_name="lessons.v2.MeService",
                input=CreateCalendarFeedRequest,
                output=CreateCalendarFeedResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_tasks(
        self,
        request: ListTasksRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListTasksResponse:
        """
        The linked account's tasks in this class, at most 200; done ones only
        when asked for.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListTasks",
                service_name="lessons.v2.MeService",
                input=ListTasksRequest,
                output=ListTasksResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def get_task(
        self,
        request: GetTaskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetTaskResponse:
        """
        RESOURCE_NOT_FOUND for somebody else's task as for one that never
        existed: an id must not reveal that a classmate keeps a list.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTask",
                service_name="lessons.v2.MeService",
                input=GetTaskRequest,
                output=GetTaskResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def create_task(
        self,
        request: CreateTaskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateTaskResponse:
        """
        `homework_id`, when set, names homework of this class (VALIDATION_FAILED
        otherwise). REST answers 201.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateTask",
                service_name="lessons.v2.MeService",
                input=CreateTaskRequest,
                output=CreateTaskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def update_task(
        self,
        request: UpdateTaskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdateTaskResponse:
        """
        `update_mask` takes title, notes, subject_name, due_date, due_time,
        priority, homework_id, remind_at and done; v1's POST /tasks/{id}/done is
        this with `done`. A path whose field is absent clears it, except title
        and priority, which cannot be cleared.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateTask",
                service_name="lessons.v2.MeService",
                input=UpdateTaskRequest,
                output=UpdateTaskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_task(
        self,
        request: DeleteTaskRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteTaskResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteTask",
                service_name="lessons.v2.MeService",
                input=DeleteTaskRequest,
                output=DeleteTaskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def create_homework_tick(
        self,
        request: CreateHomeworkTickRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateHomeworkTickResponse:
        """
        Ticks homework off for the linked account. Ticking it twice is not an
        error: the app sends the state it shows, so a retry lands on the same
        answer.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateHomeworkTick",
                service_name="lessons.v2.MeService",
                input=CreateHomeworkTickRequest,
                output=CreateHomeworkTickResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_homework_tick(
        self,
        request: DeleteHomeworkTickRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteHomeworkTickResponse:
        """
        Takes the tick off; taking off one that is not there is not an error.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteHomeworkTick",
                service_name="lessons.v2.MeService",
                input=DeleteHomeworkTickRequest,
                output=DeleteHomeworkTickResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
