# Generated from lessons/v2/substitution.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from protobuf import DescService

from . import substitution_pb
from .substitution_pb import CreateSubstitutionRequest, CreateSubstitutionResponse, DeleteSubstitutionRequest, DeleteSubstitutionResponse, GetSubstitutionRequest, GetSubstitutionResponse, ListSubstitutionsRequest, ListSubstitutionsResponse, UpdateSubstitutionRequest, UpdateSubstitutionResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class SubstitutionService(Protocol):
    async def list_substitutions(self, request: ListSubstitutionsRequest, ctx: RequestContext[ListSubstitutionsRequest, ListSubstitutionsResponse], /) -> ListSubstitutionsResponse:
        """
        Substitutions on dates in a window: today and 21 days on when unset, 62
        days at most.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_substitution(self, request: GetSubstitutionRequest, ctx: RequestContext[GetSubstitutionRequest, GetSubstitutionResponse], /) -> GetSubstitutionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def create_substitution(self, request: CreateSubstitutionRequest, ctx: RequestContext[CreateSubstitutionRequest, CreateSubstitutionResponse], /) -> CreateSubstitutionResponse:
        """
        One per date and lesson number: a second is RESOURCE_EXISTS. Refused
        with:
        - NO_LESSON_ON_DAY on a day that draws no lessons;
        - NO_BELL_FOR_LESSON at a number the day rings no bell for;
        - LESSON_NOT_ON_TIMETABLE when cancelling, or replacing without a
          subject, a lesson the day's template does not have.
        Otherwise the write would be stored, announced to every subscriber, and
        drawn nowhere. REST answers 201.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def update_substitution(self, request: UpdateSubstitutionRequest, ctx: RequestContext[UpdateSubstitutionRequest, UpdateSubstitutionResponse], /) -> UpdateSubstitutionResponse:
        """
        `update_mask` takes action, subject, room, teacher and note; the date and
        the number are the row. A path whose field is absent clears it, which
        the action cannot be; a cancellation keeps no subject, room or teacher.
        A row at a number that no longer rings stays editable, which is how a
        class gets out of one; NO_LESSON_ON_DAY and LESSON_NOT_ON_TIMETABLE are
        asked as on a create. Announced to the class's subscribers, unless
        nothing changed.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_substitution(self, request: DeleteSubstitutionRequest, ctx: RequestContext[DeleteSubstitutionRequest, DeleteSubstitutionResponse], /) -> DeleteSubstitutionResponse:
        """
        The lesson goes back to the timetable. v1: PUT /overrides with "clear".
        Announced to the class's subscribers.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in substitution_pb.desc().services if s.type_name == 'lessons.v2.SubstitutionService')

class SubstitutionServiceASGIApplication(ConnectASGIApplication[SubstitutionService]):
    def __init__(
        self,
        service: SubstitutionService | AsyncGenerator[SubstitutionService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/lessons.v2.SubstitutionService/ListSubstitutions": Endpoint.unary(
                    method=MethodInfo(
                        name="ListSubstitutions",
                        service_name="lessons.v2.SubstitutionService",
                        input=ListSubstitutionsRequest,
                        output=ListSubstitutionsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_substitutions,
                ),
                "/lessons.v2.SubstitutionService/GetSubstitution": Endpoint.unary(
                    method=MethodInfo(
                        name="GetSubstitution",
                        service_name="lessons.v2.SubstitutionService",
                        input=GetSubstitutionRequest,
                        output=GetSubstitutionResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_substitution,
                ),
                "/lessons.v2.SubstitutionService/CreateSubstitution": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateSubstitution",
                        service_name="lessons.v2.SubstitutionService",
                        input=CreateSubstitutionRequest,
                        output=CreateSubstitutionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_substitution,
                ),
                "/lessons.v2.SubstitutionService/UpdateSubstitution": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateSubstitution",
                        service_name="lessons.v2.SubstitutionService",
                        input=UpdateSubstitutionRequest,
                        output=UpdateSubstitutionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_substitution,
                ),
                "/lessons.v2.SubstitutionService/DeleteSubstitution": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteSubstitution",
                        service_name="lessons.v2.SubstitutionService",
                        input=DeleteSubstitutionRequest,
                        output=DeleteSubstitutionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_substitution,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.SubstitutionService"


class SubstitutionServiceClient(ConnectClient):
    async def list_substitutions(
        self,
        request: ListSubstitutionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListSubstitutionsResponse:
        """
        Substitutions on dates in a window: today and 21 days on when unset, 62
        days at most.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSubstitutions",
                service_name="lessons.v2.SubstitutionService",
                input=ListSubstitutionsRequest,
                output=ListSubstitutionsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_substitution(
        self,
        request: GetSubstitutionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetSubstitutionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSubstitution",
                service_name="lessons.v2.SubstitutionService",
                input=GetSubstitutionRequest,
                output=GetSubstitutionResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_substitution(
        self,
        request: CreateSubstitutionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateSubstitutionResponse:
        """
        One per date and lesson number: a second is RESOURCE_EXISTS. Refused
        with:
        - NO_LESSON_ON_DAY on a day that draws no lessons;
        - NO_BELL_FOR_LESSON at a number the day rings no bell for;
        - LESSON_NOT_ON_TIMETABLE when cancelling, or replacing without a
          subject, a lesson the day's template does not have.
        Otherwise the write would be stored, announced to every subscriber, and
        drawn nowhere. REST answers 201.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateSubstitution",
                service_name="lessons.v2.SubstitutionService",
                input=CreateSubstitutionRequest,
                output=CreateSubstitutionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_substitution(
        self,
        request: UpdateSubstitutionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdateSubstitutionResponse:
        """
        `update_mask` takes action, subject, room, teacher and note; the date and
        the number are the row. A path whose field is absent clears it, which
        the action cannot be; a cancellation keeps no subject, room or teacher.
        A row at a number that no longer rings stays editable, which is how a
        class gets out of one; NO_LESSON_ON_DAY and LESSON_NOT_ON_TIMETABLE are
        asked as on a create. Announced to the class's subscribers, unless
        nothing changed.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateSubstitution",
                service_name="lessons.v2.SubstitutionService",
                input=UpdateSubstitutionRequest,
                output=UpdateSubstitutionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_substitution(
        self,
        request: DeleteSubstitutionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteSubstitutionResponse:
        """
        The lesson goes back to the timetable. v1: PUT /overrides with "clear".
        Announced to the class's subscribers.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSubstitution",
                service_name="lessons.v2.SubstitutionService",
                input=DeleteSubstitutionRequest,
                output=DeleteSubstitutionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class SubstitutionServiceSync(Protocol):
    def list_substitutions(self, request: ListSubstitutionsRequest, ctx: RequestContext[ListSubstitutionsRequest, ListSubstitutionsResponse], /) -> ListSubstitutionsResponse:
        """
        Substitutions on dates in a window: today and 21 days on when unset, 62
        days at most.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_substitution(self, request: GetSubstitutionRequest, ctx: RequestContext[GetSubstitutionRequest, GetSubstitutionResponse], /) -> GetSubstitutionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def create_substitution(self, request: CreateSubstitutionRequest, ctx: RequestContext[CreateSubstitutionRequest, CreateSubstitutionResponse], /) -> CreateSubstitutionResponse:
        """
        One per date and lesson number: a second is RESOURCE_EXISTS. Refused
        with:
        - NO_LESSON_ON_DAY on a day that draws no lessons;
        - NO_BELL_FOR_LESSON at a number the day rings no bell for;
        - LESSON_NOT_ON_TIMETABLE when cancelling, or replacing without a
          subject, a lesson the day's template does not have.
        Otherwise the write would be stored, announced to every subscriber, and
        drawn nowhere. REST answers 201.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def update_substitution(self, request: UpdateSubstitutionRequest, ctx: RequestContext[UpdateSubstitutionRequest, UpdateSubstitutionResponse], /) -> UpdateSubstitutionResponse:
        """
        `update_mask` takes action, subject, room, teacher and note; the date and
        the number are the row. A path whose field is absent clears it, which
        the action cannot be; a cancellation keeps no subject, room or teacher.
        A row at a number that no longer rings stays editable, which is how a
        class gets out of one; NO_LESSON_ON_DAY and LESSON_NOT_ON_TIMETABLE are
        asked as on a create. Announced to the class's subscribers, unless
        nothing changed.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_substitution(self, request: DeleteSubstitutionRequest, ctx: RequestContext[DeleteSubstitutionRequest, DeleteSubstitutionResponse], /) -> DeleteSubstitutionResponse:
        """
        The lesson goes back to the timetable. v1: PUT /overrides with "clear".
        Announced to the class's subscribers.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    @classmethod
    def desc(cls) -> DescService:
        """Returns the descriptor for this service."""
        return next(s for s in substitution_pb.desc().services if s.type_name == 'lessons.v2.SubstitutionService')

class SubstitutionServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: SubstitutionServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/lessons.v2.SubstitutionService/ListSubstitutions": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListSubstitutions",
                        service_name="lessons.v2.SubstitutionService",
                        input=ListSubstitutionsRequest,
                        output=ListSubstitutionsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_substitutions,
                ),
                "/lessons.v2.SubstitutionService/GetSubstitution": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetSubstitution",
                        service_name="lessons.v2.SubstitutionService",
                        input=GetSubstitutionRequest,
                        output=GetSubstitutionResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_substitution,
                ),
                "/lessons.v2.SubstitutionService/CreateSubstitution": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateSubstitution",
                        service_name="lessons.v2.SubstitutionService",
                        input=CreateSubstitutionRequest,
                        output=CreateSubstitutionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_substitution,
                ),
                "/lessons.v2.SubstitutionService/UpdateSubstitution": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateSubstitution",
                        service_name="lessons.v2.SubstitutionService",
                        input=UpdateSubstitutionRequest,
                        output=UpdateSubstitutionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_substitution,
                ),
                "/lessons.v2.SubstitutionService/DeleteSubstitution": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteSubstitution",
                        service_name="lessons.v2.SubstitutionService",
                        input=DeleteSubstitutionRequest,
                        output=DeleteSubstitutionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_substitution,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lessons.v2.SubstitutionService"


class SubstitutionServiceClientSync(ConnectClientSync):
    def list_substitutions(
        self,
        request: ListSubstitutionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListSubstitutionsResponse:
        """
        Substitutions on dates in a window: today and 21 days on when unset, 62
        days at most.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSubstitutions",
                service_name="lessons.v2.SubstitutionService",
                input=ListSubstitutionsRequest,
                output=ListSubstitutionsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def get_substitution(
        self,
        request: GetSubstitutionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetSubstitutionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSubstitution",
                service_name="lessons.v2.SubstitutionService",
                input=GetSubstitutionRequest,
                output=GetSubstitutionResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def create_substitution(
        self,
        request: CreateSubstitutionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreateSubstitutionResponse:
        """
        One per date and lesson number: a second is RESOURCE_EXISTS. Refused
        with:
        - NO_LESSON_ON_DAY on a day that draws no lessons;
        - NO_BELL_FOR_LESSON at a number the day rings no bell for;
        - LESSON_NOT_ON_TIMETABLE when cancelling, or replacing without a
          subject, a lesson the day's template does not have.
        Otherwise the write would be stored, announced to every subscriber, and
        drawn nowhere. REST answers 201.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateSubstitution",
                service_name="lessons.v2.SubstitutionService",
                input=CreateSubstitutionRequest,
                output=CreateSubstitutionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def update_substitution(
        self,
        request: UpdateSubstitutionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> UpdateSubstitutionResponse:
        """
        `update_mask` takes action, subject, room, teacher and note; the date and
        the number are the row. A path whose field is absent clears it, which
        the action cannot be; a cancellation keeps no subject, room or teacher.
        A row at a number that no longer rings stays editable, which is how a
        class gets out of one; NO_LESSON_ON_DAY and LESSON_NOT_ON_TIMETABLE are
        asked as on a create. Announced to the class's subscribers, unless
        nothing changed.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateSubstitution",
                service_name="lessons.v2.SubstitutionService",
                input=UpdateSubstitutionRequest,
                output=UpdateSubstitutionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_substitution(
        self,
        request: DeleteSubstitutionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteSubstitutionResponse:
        """
        The lesson goes back to the timetable. v1: PUT /overrides with "clear".
        Announced to the class's subscribers.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSubstitution",
                service_name="lessons.v2.SubstitutionService",
                input=DeleteSubstitutionRequest,
                output=DeleteSubstitutionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
