# Generated from lessons/v2/timetable.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.6.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, NoReturn, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from . import options_pb
from ...google.api import annotations_pb

if TYPE_CHECKING:
    from protobuf import DescFile


_TimetableFields: TypeAlias = Literal["text", "lessons"]

class Timetable(Message[_TimetableFields]):
    """
    v1: TimetableExportOut.

    ```proto
    message lessons.v2.Timetable
    ```

    Attributes:
        text:
            ```proto
            string text = 1;
            ```
        lessons:
            ```proto
            int32 lessons = 2;
            ```
    """

    __slots__ = ("text", "lessons")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            text: str = "",
            lessons: int = 0,
        ) -> None:
            pass

        text: str
        lessons: int

_ImportConflictFields: TypeAlias = Literal["weekday", "existing", "incoming"]

class ImportConflict(Message[_ImportConflictFields]):
    """
    One weekday the paste would overwrite. v1: ImportConflictOut.

    ```proto
    message lessons.v2.ImportConflict
    ```

    Attributes:
        weekday:
            1 is Monday, 7 is Sunday.

            ```proto
            int32 weekday = 1;
            ```
        existing:
            ```proto
            int32 existing = 2;
            ```
        incoming:
            ```proto
            int32 incoming = 3;
            ```
    """

    __slots__ = ("weekday", "existing", "incoming")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            weekday: int = 0,
            existing: int = 0,
            incoming: int = 0,
        ) -> None:
            pass

        weekday: int
        existing: int
        incoming: int

_GetTimetableRequestFields: TypeAlias = NoReturn

class GetTimetableRequest(Message[_GetTimetableRequestFields]):
    """
    ```proto
    message lessons.v2.GetTimetableRequest
    ```
    """

    __slots__ = ()

    if TYPE_CHECKING:

        def __init__(
            self,
        ) -> None:
            pass

_GetTimetableResponseFields: TypeAlias = Literal["timetable"]

class GetTimetableResponse(Message[_GetTimetableResponseFields]):
    """
    ```proto
    message lessons.v2.GetTimetableResponse
    ```

    Attributes:
        timetable:
            ```proto
            optional lessons.v2.Timetable timetable = 1;
            ```
    """

    __slots__ = ("timetable",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            timetable: Timetable | None = None,
        ) -> None:
            pass

        timetable: Timetable | None

_ImportTimetableRequestFields: TypeAlias = Literal["text", "replace", "validate_only"]

class ImportTimetableRequest(Message[_ImportTimetableRequestFields]):
    """
    v1: TimetableImportIn, with the preview made explicit.

    ```proto
    message lessons.v2.ImportTimetableRequest
    ```

    Attributes:
        text:
            1 to 20000 characters.

            ```proto
            string text = 1;
            ```
        replace:
            Overwrite weekdays that already have lessons.

            ```proto
            bool replace = 2;
            ```
        validate_only:
            Parse and answer, write nothing.

            ```proto
            bool validate_only = 3;
            ```
    """

    __slots__ = ("text", "replace", "validate_only")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            text: str = "",
            replace: bool = False,
            validate_only: bool = False,
        ) -> None:
            pass

        text: str
        replace: bool
        validate_only: bool

_ImportTimetableResponseFields: TypeAlias = Literal["applied", "days", "lessons", "bells", "conflicts", "rejected"]

class ImportTimetableResponse(Message[_ImportTimetableResponseFields]):
    """
    v1: TimetableImportOut.

    ```proto
    message lessons.v2.ImportTimetableResponse
    ```

    Attributes:
        applied:
            False when nothing was written.

            ```proto
            bool applied = 1;
            ```
        days:
            The weekdays the paste names, 1 to 7.

            ```proto
            repeated int32 days = 2 [packed = true];
            ```
        lessons:
            The lessons written. When nothing was, the lessons the paste holds: a
            lesson with no bell to ring it is found only when the paste is applied.

            ```proto
            int32 lessons = 3;
            ```
        bells:
            ```proto
            int32 bells = 4;
            ```
        conflicts:
            ```proto
            repeated lessons.v2.ImportConflict conflicts = 5;
            ```
        rejected:
            Lines the parser could not read, then one line per lesson dropped for
            having no bell and per stored lesson the new bells no longer ring: an
            admin fixes the typos rather than re-reading the whole paste. When
            nothing was written, the parser's lines alone.

            ```proto
            repeated string rejected = 6;
            ```
    """

    __slots__ = ("applied", "days", "lessons", "bells", "conflicts", "rejected")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            applied: bool = False,
            days: list[int] | None = None,
            lessons: int = 0,
            bells: int = 0,
            conflicts: list[ImportConflict] | None = None,
            rejected: list[str] | None = None,
        ) -> None:
            pass

        applied: bool
        days: list[int]
        lessons: int
        bells: int
        conflicts: list[ImportConflict]
        rejected: list[str]


_DESC = file_desc(
    b'\n\x1alessons/v2/timetable.proto\x12\nlessons.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x18lessons/v2/options.proto"9\n\tTimetable\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\x12\x18\n\x07lessons\x18\x02 \x01(\x05R\x07lessons"b\n\x0eImportConflict\x12\x18\n\x07weekday\x18\x01 \x01(\x05R\x07weekday\x12\x1a\n\x08existing\x18\x02 \x01(\x05R\x08existing\x12\x1a\n\x08incoming\x18\x03 \x01(\x05R\x08incoming"\x15\n\x13GetTimetableRequest"K\n\x14GetTimetableResponse\x123\n\ttimetable\x18\x01 \x01(\x0b2\x15.lessons.v2.TimetableR\ttimetable"k\n\x16ImportTimetableRequest\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\x12\x18\n\x07replace\x18\x02 \x01(\x08R\x07replace\x12#\n\rvalidate_only\x18\x03 \x01(\x08R\x0cvalidateOnly"\xcd\x01\n\x17ImportTimetableResponse\x12\x18\n\x07applied\x18\x01 \x01(\x08R\x07applied\x12\x12\n\x04days\x18\x02 \x03(\x05R\x04days\x12\x18\n\x07lessons\x18\x03 \x01(\x05R\x07lessons\x12\x14\n\x05bells\x18\x04 \x01(\x05R\x05bells\x128\n\tconflicts\x18\x05 \x03(\x0b2\x1a.lessons.v2.ImportConflictR\tconflicts\x12\x1a\n\x08rejected\x18\x06 \x03(\tR\x08rejected2\x99\x02\n\x10TimetableService\x12y\n\x0cGetTimetable\x12\x1f.lessons.v2.GetTimetableRequest\x1a .lessons.v2.GetTimetableResponse"&\x90\x02\x01\x88\xb5\x18\x02\x90\xb5\x18\x03\x82\xd3\xe4\x93\x02\x15\x12\x13/v2/class/timetable\x12\x89\x01\n\x0fImportTimetable\x12".lessons.v2.ImportTimetableRequest\x1a#.lessons.v2.ImportTimetableResponse"-\x88\xb5\x18\x02\x90\xb5\x18\x03\x82\xd3\xe4\x93\x02\x1f:\x01*"\x1a/v2/class/timetable:importB(\n$com.lumenpearson.lessons.contract.v2P\x01b\x06proto3',
    [
        annotations_pb.desc(),
        options_pb.desc(),
    ],
    {
        "Timetable": Timetable,
        "ImportConflict": ImportConflict,
        "GetTimetableRequest": GetTimetableRequest,
        "GetTimetableResponse": GetTimetableResponse,
        "ImportTimetableRequest": ImportTimetableRequest,
        "ImportTimetableResponse": ImportTimetableResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `lessons/v2/timetable.proto`."""
    return _DESC
