# Generated from lessons/v2/watch.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.6.0 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, NoReturn, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc
from protobuf.wkt.google.protobuf import timestamp_pb

from . import options_pb

if TYPE_CHECKING:
    from protobuf import DescFile
    from protobuf.wkt.google.protobuf.timestamp_pb import Timestamp


_WatchClassRequestFields: TypeAlias = NoReturn

class WatchClassRequest(Message[_WatchClassRequestFields]):
    """
    ```proto
    message lessons.v2.WatchClassRequest
    ```
    """

    __slots__ = ()

    if TYPE_CHECKING:

        def __init__(
            self,
        ) -> None:
            pass

_WatchClassResponseFields: TypeAlias = Literal["revision", "changed_at"]

class WatchClassResponse(Message[_WatchClassResponseFields]):
    """
    ```proto
    message lessons.v2.WatchClassResponse
    ```

    Attributes:
        revision:
            Changes whenever the class does. Opaque: compare it, never parse it.

            ```proto
            string revision = 1;
            ```
        changed_at:
            ```proto
            optional google.protobuf.Timestamp changed_at = 2;
            ```
    """

    __slots__ = ("revision", "changed_at")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            revision: str = "",
            changed_at: Timestamp | None = None,
        ) -> None:
            pass

        revision: str
        changed_at: Timestamp | None


_DESC = file_desc(
    b'\n\x16lessons/v2/watch.proto\x12\nlessons.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18lessons/v2/options.proto"\x13\n\x11WatchClassRequest"k\n\x12WatchClassResponse\x12\x1a\n\x08revision\x18\x01 \x01(\tR\x08revision\x129\n\nchanged_at\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampR\tchangedAt2g\n\x0cWatchService\x12W\n\nWatchClass\x12\x1d.lessons.v2.WatchClassRequest\x1a\x1e.lessons.v2.WatchClassResponse"\x08\x88\xb5\x18\x02\x90\xb5\x18\x010\x01B(\n$com.lumenpearson.lessons.contract.v2P\x01b\x06proto3',
    [
        timestamp_pb.desc(),
        options_pb.desc(),
    ],
    {
        "WatchClassRequest": WatchClassRequest,
        "WatchClassResponse": WatchClassResponse,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `lessons/v2/watch.proto`."""
    return _DESC
