"""Encryption at rest for the one credential this project has to keep.

Everything else here is a hash. Device tokens, diary session tokens and join
codes are all stored as SHA-256 and compared by hashing what arrives, because
nothing ever needs to read them back — which is the right shape for a secret
and is why none of them needed this file.

The Petersburg diary's session token is the exception, and it is not a small
one. It has to be *replayed* to the upstream on every call, so it has to be
recoverable, which means a database dump of `diary_sessions` is a pile of live
credentials to somebody else's service holding somebody else's child's marks.
That was tolerable while the diary was one family's Android session. It stops
being tolerable the moment a whole class signs in through a bot.

So the column is sealed with Fernet — AES-128-CBC with an HMAC over the
ciphertext, versioned and timestamped by the library, so a truncated or edited
blob fails to open rather than decrypting to something. The key comes from
``DIARY_SECRET`` in the environment, the same place ``BOT_TOKEN`` and
``CRON_SECRET`` live, and never from the repository.

**No key means the diary is off, not that it falls back to plaintext.** A
fallback would be invisible: everything keeps working, the feature keeps
answering, and the only difference is a column nobody looks at. Deployments
stay in that state for years. Refusing at the door is loud on the first day and
silent afterwards, which is the way round a security default should fail.
"""

from __future__ import annotations

import base64
import hashlib
import logging

from cryptography.fernet import Fernet, InvalidToken

from app.config import MIN_DIARY_SECRET_LENGTH, get_settings

log = logging.getLogger(__name__)

#: Shortest ``DIARY_SECRET`` that is accepted.
#:
#: The key is derived by hashing the secret once, which is the right thing for
#: a value generated by ``secrets.token_urlsafe(48)`` and the wrong thing for a
#: passphrase somebody thought of. One SHA-256 pass is no defence against a
#: dictionary, so the length is a blunt filter that stops «diary» and
#: «changeme» from being a key at all.
#: Kept as a name here because this module is where it is enforced; the
#: value itself lives in `config`, so the startup log cannot disagree with the
#: cipher about what «configured» means.
MIN_SECRET_LENGTH = MIN_DIARY_SECRET_LENGTH


class DiaryEncryptionUnavailable(RuntimeError):
    """Raised when the diary is asked to work without a key configured."""


def _derive(secret: str) -> bytes:
    """A Fernet key from the configured secret.

    Hashed rather than used raw so that any string of sufficient length works —
    Fernet wants exactly 32 url-safe base64 bytes, and an operator who has to
    produce that by hand tends to produce something shorter with padding.
    """
    return base64.urlsafe_b64encode(hashlib.sha256(secret.encode("utf-8")).digest())


def cipher() -> Fernet | None:
    """The configured cipher, or ``None`` when no usable secret is set."""
    settings = get_settings()
    if not settings.diary_configured:
        return None
    return Fernet(_derive(settings.diary_secret_value))


def diary_enabled() -> bool:
    """Whether the diary may run at all on this deployment."""
    return cipher() is not None


def seal(plaintext: str) -> str:
    """Encrypt an upstream credential for storage.

    Raises rather than returning the input: a caller that stored the result
    without checking would write plaintext into a column whose whole point is
    that it is not plaintext, and nothing downstream could tell the difference.
    """
    box = cipher()
    if box is None:
        raise DiaryEncryptionUnavailable(
            "DIARY_SECRET is not set — the diary is disabled on this deployment"
        )
    return box.encrypt(plaintext.encode("utf-8")).decode("ascii")


def unseal(ciphertext: str) -> str | None:
    """Decrypt one, or ``None`` when it cannot be read.

    ``None`` covers both halves of the same situation — the key was rotated, or
    the row predates encryption — and both have the same answer: the session is
    dead and the person signs in again. That already happens every few days
    when the upstream expires its own token, so it is a path that is walked
    rather than a path that is written down and never taken.
    """
    box = cipher()
    if box is None:
        return None
    try:
        return box.decrypt(ciphertext.encode("ascii")).decode("utf-8")
    except (InvalidToken, UnicodeDecodeError, ValueError):
        log.info("diary session could not be decrypted; treating it as expired")
        return None
