"""Build the «Дневник» logo pack: every palette, every format.

    python build_pack.py            # everything (needs Chrome for the PNGs, via logo-design's render_png.py)
    python build_pack.py --no-png   # vectors, Android resources and texts only

Output: ../pack (see ../pack/README.md).
"""
import json
import math
import shutil
import subprocess
import sys
from pathlib import Path

import clock as c

HERE = Path(__file__).parent
PACK = HERE.parent / "pack"
RENDER = Path.home() / ".claude/plugins/cache/logo-design-skill/logo-design/1.4.4/skills/logo-design/scripts/render_png.py"
KEYS = list(c.PALETTES)
RECOMMENDED = "myata"


def res_name(key):
    return key.replace("-", "_")


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


# ---------------------------------------------------------------- SVG masters
def build_svg():
    for k in KEYS:
        name = c.PALETTES[k][0]
        d = PACK / "svg" / k
        write(d / f"dnevnik-{k}-symbol.svg", c.svg_doc(c.mark_svg(k), title=f"Дневник — {name}"))
        write(d / f"dnevnik-{k}-icon.svg", c.svg_doc(c.icon_svg(k), title=f"Дневник — иконка, {name}"))
        write(d / f"dnevnik-{k}-small.svg", c.svg_doc(c.mark_svg(k, small=True), title=f"Дневник — малый размер, {name}"))
        # maskable web icon: the dial inside the 80 % safe circle
        write(d / f"dnevnik-{k}-maskable.svg", c.svg_doc(c.icon_svg(k, fill=0.76), title=f"Дневник — {name}"))
    m = PACK / "svg" / "mono"
    write(m / "dnevnik-black.svg", c.svg_doc(c.mark_svg(mono="#000000", echoes=False), title="Дневник — чёрный"))
    write(m / "dnevnik-white.svg", c.svg_doc(c.mark_svg(mono="#FFFFFF", echoes=False), title="Дневник — белый"))
    write(m / "dnevnik-black-trail.svg", c.svg_doc(c.mark_svg(mono="#000000"), title="Дневник — чёрный со шлейфом"))
    write(m / "dnevnik-white-trail.svg", c.svg_doc(c.mark_svg(mono="#FFFFFF"), title="Дневник — белый со шлейфом"))
    write(m / "dnevnik-small-black.svg", c.svg_doc(c.mark_svg(mono="#000000", small=True), title="Дневник — малый, чёрный"))


# ---------------------------------------------------------------- Android VectorDrawables
def vd_color(hex_, a=1.0):
    return "#" + f"{round(a * 255):02X}" + hex_[1:].upper()


def vd_fill(g, ind):
    if g["kind"] == "linear":
        attrs = (f'android:type="linear" android:startX="{c.fmt(g["x1"])}" android:startY="{c.fmt(g["y1"])}" '
                 f'android:endX="{c.fmt(g["x2"])}" android:endY="{c.fmt(g["y2"])}"')
    else:
        attrs = (f'android:type="radial" android:centerX="{c.fmt(g["cx"])}" android:centerY="{c.fmt(g["cy"])}" '
                 f'android:gradientRadius="{c.fmt(g["r"])}"')
    items = "".join(f'\n{ind}        <item android:offset="{o}" android:color="{vd_color(col, a)}"/>'
                    for o, col, a in g["stops"])
    return (f'\n{ind}<aapt:attr name="android:fillColor">\n{ind}    <gradient {attrs}>{items}'
            f'\n{ind}    </gradient>\n{ind}</aapt:attr>')


def vd_path(d, ind, fill=None, grad=None, alpha=None, evenodd=False):
    a = f'\n{ind}    android:fillAlpha="{alpha}"' if alpha is not None else ""
    e = f'\n{ind}    android:fillType="evenOdd"' if evenodd else ""
    if grad:
        return f'{ind}<path\n{ind}    android:pathData="{d}"{a}{e}>{vd_fill(grad, ind + "    ")}\n{ind}</path>'
    return f'{ind}<path\n{ind}    android:pathData="{d}"\n{ind}    android:fillColor="{fill}"{a}{e}/>'


def vd_foreground(key=None):
    """108 dp adaptive layer; the dial's tips sit at FILL × 36 dp (inside the 33 dp safe radius ×1.0)."""
    k = c.FILL * 36 / c.R
    t = 54 - 128 * k
    mono = key is None
    if not mono:
        base, glow, echoes = c.gradients(key)
    note = ("Monochrome layer (Android 13+ themed icons): alpha carries the trail." if mono else
            f"«Дневник», palette «{c.PALETTES[key][0]}». Generated by build_pack.py — edit clock.py, not this file.")
    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f"<!-- {note}",
        "     A 12-lobe dial reading five o'clock; five turned, fading copies behind it (the trail)",
        "     are clipped by everything-but-the-cut-outs, so the hands and marks stay clean. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    xmlns:aapt="http://schemas.android.com/aapt"',
        '    android:width="108dp"', '    android:height="108dp"',
        '    android:viewportWidth="108"', '    android:viewportHeight="108">',
        f'    <group\n        android:scaleX="{k:.5f}"\n        android:scaleY="{k:.5f}"\n'
        f'        android:translateX="{t:.4f}"\n        android:translateY="{t:.4f}">',
        "        <group>",
        f'            <clip-path android:pathData="{c.holes_clip_d()}"/>',
    ]
    for i, (rot, sc, alpha) in enumerate(c.ECHOES):
        if mono:
            out.append(vd_path(c.dial(rot, sc), " " * 12, fill="#FFFFFFFF", alpha=alpha))
        else:
            out.append(vd_path(c.dial(rot, sc), " " * 12, grad=echoes[i], alpha=alpha))
    out.append("        </group>")
    body = c.body_d()
    if mono:
        out.append(vd_path(body, " " * 8, fill="#FFFFFFFF", evenodd=True))
    else:
        out.append(vd_path(body, " " * 8, grad=base, evenodd=True))
        out.append(vd_path(body, " " * 8, grad=glow, evenodd=True))
    out += ["    </group>", "</vector>", ""]
    return "\n".join(out)


def build_android():
    res = PACK / "android" / "res"
    write(res / "values" / "ic_launcher_background_white.xml",
          '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
          '    <color name="ic_launcher_background_white">#FFFFFF</color>\n</resources>\n')
    write(res / "drawable" / "ic_launcher_monochrome.xml", vd_foreground(None))
    for k in KEYS:
        rn = res_name(k)
        write(res / "drawable" / f"ic_launcher_foreground_{rn}.xml", vd_foreground(k))
        adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n'
                    '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
                    '    <background android:drawable="@color/ic_launcher_background_white"/>\n'
                    f'    <foreground android:drawable="@drawable/ic_launcher_foreground_{rn}"/>\n'
                    '    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>\n'
                    '</adaptive-icon>\n')
        write(res / "mipmap-anydpi-v26" / f"ic_launcher_{rn}.xml", adaptive)
        write(res / "mipmap-anydpi-v26" / f"ic_launcher_{rn}_round.xml", adaptive)


# ---------------------------------------------------------------- previews
def cell(x, y, size, inner, mask="circle", uid="", shadow=True):
    if mask == "circle":
        shape = '<circle cx="128" cy="128" r="128"/>'
    elif mask == "squircle":
        from icon import squircle
        shape = f'<path d="{squircle(0, 0, 256)}"/>'
    else:
        shape = '<rect width="256" height="256"/>'
    sh = (f'<filter id="sh{uid}" x="-20%" y="-20%" width="140%" height="150%"><feDropShadow dx="0" dy="4" '
          f'stdDeviation="6" flood-color="#1B2050" flood-opacity=".2"/></filter>') if shadow else ""
    pad = size * 12 / 256   # the shadow margin sits outside, so the icon itself is exactly `size` px
    return (f'<svg x="{x - pad:.2f}" y="{y - pad:.2f}" width="{size + 2 * pad:.2f}" height="{size + 2 * pad:.2f}" '
            f'viewBox="-12 -12 280 280" overflow="visible">'
            f'<defs><clipPath id="cp{uid}">{shape}</clipPath>{sh}</defs>'
            f'<g{f" filter=\"url(#sh{uid})\"" if shadow else ""}><g clip-path="url(#cp{uid})">{inner}</g></g></svg>')


def text(x, y, t, size=20, fill="#3A3F5C", weight=400, anchor="middle"):
    return (f'<text x="{x}" y="{y}" text-anchor="{anchor}" font-family="Segoe UI, Roboto, sans-serif" '
            f'font-size="{size}" font-weight="{weight}" fill="{fill}">{t}</text>')


def overview():
    W, H = 1600, 1330
    p = [f'<rect width="{W}" height="{H}" fill="#EEF0F7"/>',
         text(60, 70, "Дневник — комплект логотипа", 38, "#1D2140", 700, "start"),
         text(60, 108, "Пятёрка: 12 лепестков, ровно 5:00 · восемь палитр · Android, Google Play, веб", 20,
              "#5A5F7C", 400, "start"),
         '<rect x="40" y="140" width="1520" height="760" rx="40" fill="#DCE2F5"/>']
    for i, k in enumerate(KEYS):
        x = 95 + (i % 4) * 370
        y = 175 + (i // 4) * 360
        p.append(cell(x, y, 270, c.icon_svg(k, p=f"o{i}_"), uid=f"o{i}"))
        label = c.PALETTES[k][0] + ("  ★" if k == RECOMMENDED else "")
        p.append(text(x + 135, y + 315, label, 22, "#2A2F4C", 600))
    y0 = 945
    p.append(text(60, y0, "Тематическая (Android 13+)", 20, "#3A3F5C", 600, "start"))
    p.append(cell(60, y0 + 20, 170, c.icon_svg(mono="#3F4A84", bg="#E3E1EC", p="th1_"), uid="th1"))
    p.append(cell(250, y0 + 20, 170, c.icon_svg(mono="#CAC4F5", bg="#2B2A33", p="th2_"), uid="th2"))
    p.append(text(470, y0, "Маски лаунчеров", 20, "#3A3F5C", 600, "start"))
    p.append(cell(470, y0 + 20, 170, c.icon_svg(RECOMMENDED, p="sq_"), mask="squircle", uid="sq"))
    p.append(cell(660, y0 + 20, 170, c.icon_svg(RECOMMENDED, p="rc_"), mask="rect", uid="rc"))
    p.append(text(880, y0, "Размеры", 20, "#3A3F5C", 600, "start"))
    x = 880
    for j, s in enumerate((96, 64, 48, 32, 24)):
        p.append(cell(x, y0 + 20 + (96 - s) / 2, s, c.icon_svg(RECOMMENDED, p=f"z{j}_"), uid=f"z{j}"))
        p.append(text(x + s / 2, y0 + 150, f"{s}", 16, "#6A6F8C"))
        x += s + 30
    p.append(text(1330, y0, "Малый вариант ≤ 32 px", 20, "#3A3F5C", 600, "start"))
    x = 1330
    for j, s in enumerate((48, 32, 16)):
        p.append(cell(x, y0 + 20 + (48 - s) / 2, s, c.icon_svg(RECOMMENDED, small=True, p=f"m{j}_"),
                      uid=f"m{j}", shadow=False))
        p.append(text(x + s / 2, y0 + 100, f"{s}", 16, "#6A6F8C"))
        x += s + 40
    y1 = 1150
    p.append(f'<rect x="40" y="{y1}" width="1520" height="150" rx="32" fill="#1C1E2B"/>')
    for i, k in enumerate(KEYS):
        p.append(cell(80 + i * 185, y1 + 22, 106, c.icon_svg(k, p=f"dk{i}_"), uid=f"dk{i}"))
    return c.svg_doc("".join(p), W, H, "Дневник — обзор комплекта")


def detail():
    W, H = 1400, 720
    p = [f'<rect width="{W}" height="{H}" fill="#FFFFFF"/>',
         f'<svg x="40" y="40" width="640" height="640" viewBox="0 0 256 256">{c.mark_svg(mono="#14182E")}</svg>',
         f'<svg x="720" y="40" width="640" height="640" viewBox="0 0 256 256">{c.mark_svg(RECOMMENDED, p="dt_")}</svg>']
    return c.svg_doc("".join(p), W, H, "Дневник — построение")


def build_previews():
    write(PACK / "previews" / "overview.svg", overview())
    write(PACK / "previews" / "detail.svg", detail())


# ---------------------------------------------------------------- web
def build_web_texts():
    for k in KEYS:
        d = PACK / "web" / k
        manifest = {
            "name": "Дневник", "short_name": "Дневник",
            "icons": [
                {"src": "icon-192.png", "sizes": "192x192", "type": "image/png"},
                {"src": "icon-512.png", "sizes": "512x512", "type": "image/png"},
                {"src": "maskable-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable"},
            ],
            "theme_color": "#FFFFFF", "background_color": "#FFFFFF", "display": "standalone",
        }
        write(d / "site.webmanifest", json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
        write(d / "head-snippet.html",
              '<link rel="icon" href="/favicon.ico" sizes="any">\n'
              '<link rel="icon" href="/favicon.svg" type="image/svg+xml">\n'
              '<link rel="apple-touch-icon" href="/apple-touch-icon.png">\n'
              '<link rel="manifest" href="/site.webmanifest">\n'
              '<meta name="theme-color" content="#FFFFFF">\n')
        shutil.copyfile(PACK / "svg" / k / f"dnevnik-{k}-small.svg", d / "favicon.svg")


# ---------------------------------------------------------------- PNG (Chrome via render_png.py)
def render(files, size, out_dir, bg=None):
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = [sys.executable, str(RENDER), *map(str, files), "--out-dir", str(out_dir), "--size", str(size)]
    if bg:
        cmd += ["--bg", bg]
    subprocess.run(cmd, check=True, capture_output=True)


def render_one(src, out, w, h):
    subprocess.run([sys.executable, str(RENDER), str(src), "-o", str(out), "--width", str(w), "--height", str(h)],
                   check=True, capture_output=True)


def build_png():
    tmp = PACK / "_tmp"
    syms = [PACK / "svg" / k / f"dnevnik-{k}-symbol.svg" for k in KEYS]
    icons = [PACK / "svg" / k / f"dnevnik-{k}-icon.svg" for k in KEYS]
    smalls = [PACK / "svg" / k / f"dnevnik-{k}-small.svg" for k in KEYS]
    masks = [PACK / "svg" / k / f"dnevnik-{k}-maskable.svg" for k in KEYS]
    monos = sorted((PACK / "svg" / "mono").glob("*.svg"))
    jobs = [(syms + monos, 1024, "sym1024"), (syms + monos, 512, "sym512"), (syms, 256, "sym256"),
            (icons, 512, "icon512"), (icons, 192, "icon192"), (icons, 180, "icon180"),
            (masks, 512, "mask512"), (smalls, 48, "s48"), (smalls, 32, "s32"), (smalls, 16, "s16")]
    for files, size, tag in jobs:
        render(files, size, tmp / tag)
    for k in KEYS:
        pd, wd = PACK / "png" / k, PACK / "web" / k
        pd.mkdir(parents=True, exist_ok=True)
        for s in (1024, 512, 256):
            shutil.copyfile(tmp / f"sym{s}" / f"dnevnik-{k}-symbol.png", pd / f"dnevnik-{k}-symbol-{s}.png")
        shutil.copyfile(tmp / "icon512" / f"dnevnik-{k}-icon.png", pd / f"dnevnik-{k}-play-store-512.png")
        shutil.copyfile(tmp / "icon512" / f"dnevnik-{k}-icon.png", wd / "icon-512.png")
        shutil.copyfile(tmp / "icon192" / f"dnevnik-{k}-icon.png", wd / "icon-192.png")
        shutil.copyfile(tmp / "icon180" / f"dnevnik-{k}-icon.png", wd / "apple-touch-icon.png")
        shutil.copyfile(tmp / "mask512" / f"dnevnik-{k}-maskable.png", wd / "maskable-512.png")
        for s in (16, 32, 48):
            shutil.copyfile(tmp / f"s{s}" / f"dnevnik-{k}-small.png", wd / f"favicon-{s}.png")
        subprocess.run([sys.executable, str(RENDER), str(PACK / "svg" / k / f"dnevnik-{k}-small.svg"),
                        "--ico", str(wd / "favicon.ico"), "--ico-sizes", "16", "32", "48"],
                       check=True, capture_output=True)
    md = PACK / "png" / "mono"
    md.mkdir(parents=True, exist_ok=True)
    for f in monos:
        for s in (1024, 512):
            shutil.copyfile(tmp / f"sym{s}" / f"{f.stem}.png", md / f"{f.stem}-{s}.png")
    render_one(PACK / "previews" / "overview.svg", PACK / "previews" / "overview.png", 1600, 1330)
    render_one(PACK / "previews" / "detail.svg", PACK / "previews" / "detail.png", 1400, 720)
    shutil.rmtree(tmp)


def write_readme():
    rows = ["| Вариант | Папка / ресурс | Центр и верх · кольцо 53 % · край |", "| --- | --- | --- |"]
    for k in KEYS:
        name, stops = c.PALETTES[k]
        star = " ★" if k == RECOMMENDED else ""
        rows.append(f"| {name}{star} | `{k}` / `{res_name(k)}` | " + " · ".join(f"`{h}`" for h in stops) + " |")
    text = (HERE / "pack-readme.md").read_text(encoding="utf-8").replace("{{TABLE}}", "\n".join(rows))
    write(PACK / "README.md", text)


if __name__ == "__main__":
    if PACK.exists():
        shutil.rmtree(PACK)
    build_svg()
    build_android()
    build_previews()
    build_web_texts()
    write_readme()
    if "--no-png" not in sys.argv:
        build_png()
    print("pack:", PACK)
