import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/*
 * The application module. It owns nothing but glue: the Application object, the
 * single Activity, navigation and the feature screens. Everything durable
 * (models, storage, sync, design tokens, widget) lives in the modules below it,
 * which is what keeps this file short and the build incremental.
 */
plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

composeCompiler {
    // Why this file exists, and what is deliberately left out of it, is written
    // at the top of `compose-stability.conf`. Named in every Compose module
    // rather than from the root build: cross-configuring subprojects is what
    // this build has always avoided.
    stabilityConfigurationFiles.add(
        rootProject.layout.projectDirectory.file("compose-stability.conf"),
    )
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_21)
        // Material 3 Expressive is still gated behind opt-in annotations; the app
        // is built against it deliberately, so opt in once here instead of
        // sprinkling @OptIn over every composable.
        optIn.addAll(
            "androidx.compose.material3.ExperimentalMaterial3Api",
            "androidx.compose.material3.ExperimentalMaterial3ExpressiveApi",
            "androidx.compose.foundation.ExperimentalFoundationApi",
            "androidx.compose.foundation.layout.ExperimentalLayoutApi",
            "androidx.compose.ui.text.ExperimentalTextApi",
        )
    }
}

/*
 * Release signing.
 *
 * Credentials are read from environment variables (what CI sets) or Gradle
 * properties (what `~/.gradle/gradle.properties` holds locally). Both are
 * configuration-cache-tracked providers, and neither lives in the repository,
 * so there is no keystore or password to leak in a commit.
 *
 * When nothing is configured the release build is signed with the debug key
 * instead of being left unsigned. An unsigned APK cannot be installed at all,
 * which makes "build me an APK" fail for the common case of a fresh clone with
 * no secrets set up. A debug-signed release is installable and still gets the
 * real R8 treatment; it simply must not be published, which the build warns
 * about and the workflow repeats in its summary.
 *
 * What that fallback does *not* give is an update. The debug keystore is
 * generated by the tooling on the machine that builds, the first time it is
 * needed: the alias and the passwords are constants, the key pair is not. A CI
 * runner is a fresh machine every time and the Gradle cache covers `~/.gradle`
 * rather than `~/.android`, so two debug-signed builds of this app carry two
 * different certificates and Android refuses to install either over the other —
 * whatever `versionCode` says, since the certificate is compared first. Only
 * uninstalling helps, and it takes the device's classes and tokens with it. See
 * docs/build.md, "A debug-signed build is never an update of another one".
 */
fun signingSecret(env: String, property: String): String? =
    (providers.environmentVariable(env).orNull ?: providers.gradleProperty(property).orNull)
        ?.takeIf { it.isNotBlank() }

val keystorePath = signingSecret("LESSONS_KEYSTORE_FILE", "lessons.keystore.file")
val keystorePassword = signingSecret("LESSONS_KEYSTORE_PASSWORD", "lessons.keystore.password")
val keystoreKeyAlias = signingSecret("LESSONS_KEY_ALIAS", "lessons.key.alias")
val keystoreKeyPassword = signingSecret("LESSONS_KEY_PASSWORD", "lessons.key.password")

val hasReleaseSigning: Boolean =
    keystorePath != null &&
        keystorePassword != null &&
        keystoreKeyAlias != null &&
        keystoreKeyPassword != null &&
        File(keystorePath).exists()

// Version identity can be overridden per build so a tagged release APK is
// distinguishable from a nightly one. Both fall back to the values below.
val appVersionName = signingSecret("LESSONS_VERSION_NAME", "lessons.versionName") ?: "0.1.0"

// Refuses rather than falling back. `toIntOrNull() ?: 1` was the whole rule,
// and the number it silently swallowed is exactly the one somebody gets wrong:
// `2147483648` is one past what an Int holds, passes the workflow's "digits
// only" check, and used to leave the APK stamped versionCode 1 — which installs
// over nothing and is never an update of anything. A raised number that does not
// arrive is invisible until a phone refuses the install, so it is a build
// failure here instead. The ceiling is Google Play's 2100000000, below Int's own
// maximum, because an APK above it cannot be published at all.
val maxVersionCode = 2_100_000_000

val appVersionCode =
    signingSecret("LESSONS_VERSION_CODE", "lessons.versionCode")?.let { raw ->
        raw.toIntOrNull()?.takeIf { it in 1..maxVersionCode }
            ?: throw GradleException(
                "LESSONS_VERSION_CODE / lessons.versionCode is \"$raw\"; " +
                    "it must be a whole number between 1 and $maxVersionCode.",
            )
    } ?: 1

// The GitHub OAuth App the "sign in with GitHub" row talks to. Whoever builds
// the app registers one (Settings → Developer settings → OAuth Apps, with
// "Enable Device Flow" ticked) and passes its client id here. There is no
// secret: the device flow does not use one, and an APK could not keep it
// anyway. Empty means the row does not appear.
val githubClientId = signingSecret("LESSONS_GITHUB_CLIENT_ID", "lessons.github.clientId") ?: ""

// Where "отправить письмом" on the bug-report sheet goes. Not in the source
// for the same reason the keystore is not: an address in a public repository
// is an address on every spam list, and it is the builder's to give. Empty
// hides the button.
val contactEmail = signingSecret("LESSONS_CONTACT_EMAIL", "lessons.contactEmail") ?: ""

android {
    namespace = "com.lumenpearson.lessons"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.lumenpearson.lessons"
        minSdk = 26
        targetSdk = 37
        versionCode = appVersionCode
        versionName = appVersionName
        buildConfigField("String", "GITHUB_CLIENT_ID", "\"$githubClientId\"")
        buildConfigField("String", "CONTACT_EMAIL", "\"$contactEmail\"")
    }

    androidResources {
        // The app is Russian-first with an English fallback; shipping only these
        // two keeps the APK free of the transitive AndroidX translations.
        localeFilters += listOf("ru", "en")
    }

    signingConfigs {
        if (hasReleaseSigning) {
            create("release") {
                storeFile = File(keystorePath!!)
                storePassword = keystorePassword
                keyAlias = keystoreKeyAlias
                keyPassword = keystoreKeyPassword
                // Both schemes: v1 for API 26-27 devices, v2+ for everything since.
                enableV1Signing = true
                enableV2Signing = true
            }
        }
    }

    buildTypes {
        debug {
            // Suffixed so a debug build can sit next to a release install — the
            // widget is much easier to develop with both present.
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
            isMinifyEnabled = false
        }
        release {
            signingConfig = if (hasReleaseSigning) {
                signingConfigs.getByName("release")
            } else {
                logger.warn(
                    "No release keystore configured; signing the release build with the " +
                        "debug key so the APK is installable. Do not publish this artifact - " +
                        "see docs/build.md to set up real signing.",
                )
                signingConfigs.getByName("debug")
            }
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    buildFeatures {
        compose = true
        // BuildConfig.VERSION_NAME is what the "О приложении" section renders.
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }

    testOptions {
        // Robolectric needs this module's own resources on the test classpath.
        // Every screen here is built out of Russian strings, and a test that
        // cannot resolve them is a test asserting against stubs - which on
        // these screens would mean asserting nothing at all. Which Android it
        // emulates is pinned in `src/test/resources/robolectric.properties`,
        // beside the reason.
        unitTests.isIncludeAndroidResources = true
    }
}

// `BuildPropertyReachTest` reads this file and the APK workflow, neither of
// which Gradle would otherwise know this task depends on - so a change to
// either left the task UP-TO-DATE and the check unrun, which for a test whose
// whole subject is a wire nobody noticed was broken is the same failure twice.
// CI gets a fresh checkout and would have run it anyway; a laptop would not.
tasks.withType<Test>().configureEach {
    inputs.file(layout.projectDirectory.file("build.gradle.kts"))
        .withPropertyName("appBuildScript")
        .withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(rootProject.layout.projectDirectory.file("../.github/workflows/apk.yml"))
        .withPropertyName("apkWorkflow")
        .withPathSensitivity(PathSensitivity.RELATIVE)
}

dependencies {
    implementation(project(":core:model"))
    implementation(project(":core:data"))
    implementation(project(":core:designsystem"))
    // Brought in so the widget's receiver is merged into the app manifest and
    // the widget ships in the same APK; the app never calls into it directly.
    implementation(project(":widget"))

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.foundation)
    // material3 carries its own version in the catalog on purpose: the BOM would
    // otherwise pin a non-Expressive build.
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.androidx.compose.ui.tooling.preview)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    // WorkManager is scheduled from Application.onCreate through SyncScheduler.
    implementation(libs.androidx.work.runtime.ktx)
    implementation(libs.kotlinx.coroutines.android)

    debugImplementation(libs.androidx.compose.ui.tooling)

    testImplementation(libs.junit)
    // The management view model is a coroutine state holder: its tests need a
    // main dispatcher and a scheduler they can step, which is all this is for.
    testImplementation(libs.kotlinx.coroutines.test)

    // The same harness `:core:designsystem` already runs, moved up a layer.
    // That module can prove a row reports its click; it cannot prove that the
    // screen built out of those rows shows the right class, refuses to switch a
    // class code off without asking, or says a refused code in words a person
    // can act on. Those are decisions, they live here, and until now the only
    // thing that could check one was somebody holding a phone.
    testImplementation(libs.robolectric)
    testImplementation(platform(libs.androidx.compose.bom))
    testImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
}
