"""The region catalog: generated from the survey, committed, and read by both halves.

`app/catalog/data/regions.json` is what the phone's onboarding lists, searches and
recommends from, and what the server's school directory places a school with. It
is generated by `scripts/region_catalog.py` from `docs/diaries/regions.md`, the
netschool allow-list and a hand overlay, and every decision in it — which system
can be signed into, which is handed off to Госуслуги, which is put first — is
made there and read everywhere else.

Three kinds of test live here. The drift test, which makes a survey edit without
the regenerated catalog a red build. The contract tests, which hold the catalog to
the things other code stores or trusts: region keys that sit in database columns,
origins a sign-in may go to, zones, DaData's spellings. And the parser tests,
which pin the traps the survey's markdown sets — a full stop inside «Since», a
label that is itself «Е-услуги. Образование», a port, an IDN and its punycode twin,
one page that means two platforms.
"""

from __future__ import annotations

import fnmatch
import functools
import json
import re
import tomllib
from collections import Counter
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

import pytest

from app import catalog
from app.providers.diary import registry
from app.providers.netschool import regions as allow_list
from app.providers.petersburg.client import BASE_URL as PETERSBURG_ORIGIN
from scripts import region_catalog as generator

ROOT = Path(__file__).resolve().parents[2]
SERVER = ROOT / "server"


@functools.cache
def _overlay() -> dict[str, Any]:
    return tomllib.loads(generator.OVERLAY.read_text(encoding="utf-8"))


@functools.cache
def _built_text() -> str:
    return generator.render(generator.build_from_repository())


@functools.cache
def _committed_text() -> str:
    return catalog.DATA.read_text(encoding="utf-8")


def _committed() -> dict[str, Any]:
    # A fresh parse each time: a test that edits what it is handed must not edit
    # what the next test reads.
    return json.loads(_committed_text())


def _regions() -> dict[str, dict[str, Any]]:
    return {region["key"]: region for region in _committed()["regions"]}


def _systems() -> list[tuple[dict[str, Any], dict[str, Any]]]:
    return [(region, system) for region in _committed()["regions"] for system in region["systems"]]


def _headings() -> list[str]:
    text = generator.REGIONS_MD.read_text(encoding="utf-8")
    return re.findall(r"^## (.+?)\s*$", text, flags=re.MULTILINE)


# --------------------------------------------------------------------------
# The committed file
# --------------------------------------------------------------------------


def test_the_committed_catalog_is_what_the_generator_writes():
    """A survey edit that is not followed by `python -m scripts.region_catalog` fails here.

    The phone bundles the committed file, so a regions.md fix that never reached
    the JSON is a fix no family sees — and the same holds for regions.py: an
    origin moved in the allow-list and not in the catalog leaves the phone
    signing in somewhere the server refuses to follow.
    """
    assert _committed_text() == _built_text(), (
        "app/catalog/data/regions.json is stale: run `python -m scripts.region_catalog` "
        "from server/ and commit the result"
    )


def test_the_check_flag_fails_on_a_catalog_that_drifted(tmp_path, monkeypatch, capsys):
    stale = tmp_path / "regions.json"
    stale.write_text(_built_text().replace('"leningrad"', '"lenobl"', 1), encoding="utf-8")
    monkeypatch.setattr(generator, "OUTPUT", stale)
    monkeypatch.setattr(generator, "ROOT", tmp_path)

    assert generator.main(["--check"]) == 1
    assert "is not what the survey implies" in capsys.readouterr().err

    stale.write_text(_built_text(), encoding="utf-8")
    assert generator.main(["--check"]) == 0


def test_eighty_nine_regions_in_the_survey_order():
    regions = _committed()["regions"]

    assert len(regions) == 89
    assert [region["name_ru"] for region in regions] == _headings()
    assert [region["order"] for region in regions] == list(range(1, 90))
    # Art. 65 order, which is not alphabetical: Russian collation would file
    # every «Республика …» under Р, and the survey's first region is a republic.
    assert regions[0]["key"] == "adygea" and regions[-1]["key"] == "yanao"
    assert sum(region["mandatory"] for region in regions) == 13


def test_keys_are_unique_slugs_and_codes_unique_two_digits():
    regions = _committed()["regions"]
    keys = [region["key"] for region in regions]
    codes = [region["code"] for region in regions]

    assert len(set(keys)) == 89
    assert len(set(codes)) == 89
    for region in regions:
        # The width of classes.diary_region and diary_sessions.region, and the
        # pattern the registration body checks a region against.
        assert re.fullmatch(r"[a-z0-9-]{2,32}", region["key"]), region["key"]
        assert re.fullmatch(r"\d\d", region["code"]), region["code"]
    assert {key: code for key, code in zip(keys, codes, strict=True)}["crimea"] == "91"
    assert {key: code for key, code in zip(keys, codes, strict=True)}["sevastopol"] == "92"


def test_the_nineteen_netschool_keys_are_the_allow_lists_own():
    """The keys the database stores, byte for byte — and everything else the phone trusts.

    `classes.diary_region`, `diary_sessions.region` and the sealed credential all
    hold these strings. A catalog key that differed by a letter would leave every
    class bound to that region looking unbound on the phone, and an origin that
    differed would be a second allow-list.
    """
    regions = _regions()
    rows = allow_list.listed(password_only=False)
    assert len(rows) == 19

    for row in rows:
        region = regions[row.key]
        assert region["name_ru"] == row.title
        (linked,) = [system for system in region["systems"] if system["netschool"]]
        assert linked["netschool"] == {
            "region": row.key,
            "origin": row.origin,
            "password": row.password,
            "verified": row.verified,
            "zone": row.zone,
        }


def test_every_allow_listed_region_appears_exactly_once():
    linked = Counter(
        system["netschool"]["region"] for _, system in _systems() if system["netschool"]
    )

    assert linked == Counter(row.key for row in allow_list.listed(password_only=False))
    for region, system in _systems():
        if system["netschool"]:
            assert system["netschool"]["region"] == region["key"]
            assert system["platform"] == "netschool"


def test_volgograd_is_listed_but_unreachable():
    """In the survey, out of the allow-list, and told apart from «not supported».

    Its «Сетевой город» serves http only and refuses datacenter addresses. The
    family should read that, not that the app has never heard of their diary.
    """
    volgograd = _regions()["volgograd"]
    (netschool,) = [s for s in volgograd["systems"] if s["platform"] == "netschool"]

    assert allow_list.get("volgograd") is None
    assert netschool["role"] == "primary"
    assert netschool["action"] == "none"
    assert netschool["netschool"] is None
    assert netschool["excluded"] == "http-only"
    assert netschool["web_url"] is None
    assert volgograd["recommended"]["reason"] == "unreachable"
    assert volgograd["recommended"]["platform"] == "netschool"
    assert [
        region["key"] for region in _committed()["regions"]
        if region["recommended"]["reason"] == "unreachable"
    ] == ["volgograd"]


def test_every_region_has_an_english_name():
    """Names in the JSON escape `ResourceTranslationTest`, so this is their twin rule."""
    cyrillic = re.compile(r"[Ѐ-ӿ]")
    for region in _committed()["regions"]:
        assert region["name_en"].strip(), region["key"]
        assert not cyrillic.search(region["name_en"]), region["name_en"]
        assert region["name_en"] != region["name_ru"]
    for key, platform in _committed()["platforms"].items():
        assert platform["name_ru"].strip() and platform["name_en"].strip(), key
        assert not cyrillic.search(platform["name_en"]), platform["name_en"]


def test_dadata_names_resolve_to_exactly_one_region():
    seen: dict[str, str] = {}
    for region in _committed()["regions"]:
        assert region["dadata_names"], region["key"]
        for name in region["dadata_names"]:
            normalised = catalog.normalise_name(name)
            assert seen.setdefault(normalised, region["key"]) == region["key"], name
            placed = catalog.by_dadata_name(name)
            assert placed is not None and placed.key == region["key"], name


def test_every_system_names_a_known_platform_and_provider_key():
    platforms = _committed()["platforms"]
    for key, platform in platforms.items():
        assert platform["provider"] in (*registry.KEYS, None), key
        assert platform["provider"] in (key, None), key
        if platform["page"] is not None:
            assert (generator.PAGES / f"{platform['page']}.md").is_file(), key
    for region, system in _systems():
        assert system["platform"] in platforms, (region["key"], system["platform"])
        assert system["role"] in ("primary", "secondary", "legacy", "migrating_to", "unclear")
        assert system["confidence"] in ("low", "medium", "high")
    assert {system["platform"] for _, system in _systems()} == set(platforms)


def test_primary_counts_match_the_platform_table():
    """Counting primaries by page reproduces docs/diaries.md's platforms table.

    ТОР and the federal portal share `myschool-federal.md`; the table's row
    counts ТОР, and the portal is never anybody's primary.
    """
    platforms = _committed()["platforms"]
    now: Counter[str] = Counter()
    moving: Counter[str] = Counter()
    for _, system in _systems():
        page = platforms[system["platform"]]["page"]
        if page is None:
            continue
        if system["role"] == "primary":
            now[page] += 1
        elif system["role"] == "migrating_to":
            moving[page] += 1

    table = generator.platform_table(generator.DIARIES_MD.read_text(encoding="utf-8"))
    assert {page: counts for page, counts in table.items() if any(counts)} == {
        page: (now[page], moving[page]) for page in set(now) | set(moving)
    }
    # The two primaries the table cannot count, because neither has a page.
    unpaged = [
        system["platform"] for _, system in _systems()
        if system["role"] == "primary" and platforms[system["platform"]]["page"] is None
    ]
    assert sorted(unpaged) == ["it-school-penza", "paper"]


def test_only_petersburg_and_password_netschool_are_signable():
    """The one place the catalog could open a door the decision record keeps shut.

    Sign-in here means the app's own form, sending a password straight to the
    provider: Petersburg, and the sixteen «Сетевой город» regions whose
    allow-list row takes a password. ТОР and the three Госуслуги-only regions
    are hand-offs to a page in the browser, and nothing about signing in to
    Госуслуги inside the app may enter the catalog in any form.
    """
    signable = {
        (region["key"], system["platform"])
        for region, system in _systems()
        if system["action"] == "signin"
    }
    password_regions = {row.key for row in allow_list.listed()}
    assert len(password_regions) == 16
    assert signable == {("saint-petersburg", "petersburg")} | {
        (key, "netschool") for key in password_regions
    }

    for region, system in _systems():
        assert system["action"] in ("signin", "handoff", "none")
        if system["role"] in ("legacy", "unclear"):
            assert system["action"] == "none", (region["key"], system["platform"])
        if system["action"] == "handoff":
            if system["platform"] == "tor-myschool":
                assert system["handoff_url"] == "https://www.gosuslugi.ru/school"
            else:
                row = allow_list.get(region["key"])
                assert system["platform"] == "netschool" and row is not None
                assert not row.password
                assert system["handoff_url"] == row.origin
        else:
            assert system["handoff_url"] is None
        if system["action"] == "signin" and system["platform"] == "petersburg":
            assert system["web_url"] == PETERSBURG_ORIGIN

    handed_to_origin = {
        region["key"] for region, system in _systems()
        if system["action"] == "handoff" and system["platform"] == "netschool"
    }
    assert handed_to_origin == {"altai-krai", "primorye", "tula"}

    for text in (_committed_text(), generator.OVERLAY.read_text(encoding="utf-8")):
        lowered = text.casefold()
        for forbidden in ("signin_surface", "webview", "на странице дневника"):
            assert forbidden not in lowered, forbidden


def test_every_address_the_phone_may_open_is_https():
    """`web_url` and `handoff_url` go to `ACTION_VIEW` as they stand.

    Волгоград's diary serves only http and so has no `web_url` at all, and a
    wildcard host such as `*.eljur.ru` is never turned into an address.
    """
    for region, system in _systems():
        for field in ("web_url", "handoff_url"):
            url = system[field]
            if url is None:
                continue
            assert url.startswith("https://"), (region["key"], field, url)
            assert "*" not in url and url.isascii(), (region["key"], field, url)


def test_tor_is_never_recommended_where_the_survey_says_it_is_absent():
    regions = _committed()["regions"]
    absent = {region["key"] for region in regions if region["tor"] == "absent"}

    assert absent == {"zaporozhye", "kherson", "sevastopol"}
    assert {region["tor"] for region in regions} <= set(generator.TOR_STATES)
    for region in regions:
        if region["tor"] == "absent":
            assert region["recommended"]["platform"] != "tor-myschool"
            assert all(system["platform"] != "tor-myschool" for system in region["systems"])


def test_zones_are_real_and_match_the_allow_list():
    regions = _regions()
    for region in regions.values():
        ZoneInfo(region["zone"])
    for row in allow_list.listed(password_only=False):
        assert regions[row.key]["zone"] == row.zone


def _ignored_by(pattern: str, relative: str) -> bool:
    """One `.vercelignore` line against one path, by gitignore's rules as Vercel reads them."""
    directory_only = pattern.endswith("/")
    core = pattern.strip("/")
    parts = relative.split("/")
    if "/" in core:
        # Anchored at the root: it names a directory by its path (or a file, if
        # it has no trailing slash).
        prefixes = ["/".join(parts[: i + 1]) for i in range(len(parts) - 1)]
        if not directory_only:
            prefixes.append(relative)
        return any(fnmatch.fnmatch(prefix, core) for prefix in prefixes)
    # Unanchored: it names a component at any depth, a directory's only if it ends in «/».
    candidates = parts[:-1] if directory_only else parts
    return any(fnmatch.fnmatch(part, core) for part in candidates)


def test_the_catalog_sits_where_vercel_ships_it():
    """Under `server/app/`, matched by nothing in `.vercelignore`, and packaged.

    `server/scripts/` is ignored on purpose — the generator never runs in a
    request — so the catalog must not live beside it, and the loader must not
    read the overlay. Whether Vercel then uploads a `.json` next to the code is
    inferred rather than seen: the first preview deploy's directory call is what
    settles it.
    """
    data = catalog.DATA.relative_to(ROOT).as_posix()
    loader = Path(catalog.__file__).resolve().relative_to(ROOT).as_posix()
    assert data.startswith("server/app/")

    patterns = [
        line.strip()
        for line in (ROOT / ".vercelignore").read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    ]
    assert _ignored_by("server/scripts/", "server/scripts/region_catalog.toml")
    for path in (data, loader):
        assert not [pattern for pattern in patterns if _ignored_by(pattern, path)], path

    pyproject = tomllib.loads((SERVER / "pyproject.toml").read_text(encoding="utf-8"))
    assert "catalog/data/*.json" in pyproject["tool"]["setuptools"]["package-data"]["app"]


# --------------------------------------------------------------------------
# What is decided
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("key", "platform", "reason", "modifiers"),
    [
        ("saint-petersburg", "petersburg", "primary", ["unverified"]),
        ("leningrad", "netschool", "primary", ["unverified"]),
        ("altai-krai", "netschool", "primary", ["esia_only"]),
        ("altai-republic", "tor-myschool", "tor_primary", []),
        ("tatarstan", "tor-myschool", "front_end", []),
        ("orenburg", "tor-myschool", "moving_to", []),
        ("volgograd", "netschool", "unreachable", []),
        ("adygea", "dnevnik-ru", "unsupported", []),
        ("moscow", "mesh-moscow", "unsupported", []),
        ("sevastopol", "paper", "no_diary", []),
    ],
)
def test_one_system_is_recommended_and_the_reason_is_a_code(key, platform, reason, modifiers):
    region = _regions()[key]
    recommended = region["recommended"]
    chosen = region["systems"][recommended["system"]]

    assert recommended["platform"] == chosen["platform"] == platform
    assert recommended["confidence"] == chosen["confidence"]
    assert recommended["reason"] == reason
    assert recommended["modifiers"] == modifiers


def test_every_reason_is_one_the_phone_has_a_sentence_for():
    for region in _committed()["regions"]:
        assert region["recommended"]["reason"] in generator.REASONS
        assert set(region["recommended"]["modifiers"]) <= set(generator.MODIFIERS)
        # A front end below «medium» is listed, and never put first.
        if region["recommended"]["reason"] == "front_end":
            chosen = region["systems"][region["recommended"]["system"]]
            assert chosen["front_end"] and chosen["confidence"] != "low", region["key"]


def test_the_school_year_follows_the_survey_month():
    assert _committed()["survey"] == {"month": "2026-09", "school_year": "2026/27"}


# --------------------------------------------------------------------------
# Reading the survey
# --------------------------------------------------------------------------

#: A survey block carrying every trap at once, in regions.md's own grammar.
_BLOCK = "\n".join(
    [
        "# Preamble that is not a region",
        "",
        "## Республика Бурятия",
        "",
        "*Mandatory region.*",
        "",
        "- **in use now: [«Сетевой город»](netschool.md)** — ГИС «Электронное образование»"
        " (ИРТех). Hosts: `deti.obr03.ru`, `sad06.ru:82`. Since: 2016/17 (decree of"
        " 01.12.2016 № 549). Confidence: high.",
        "  deti.obr03.ru answered 403. Hosts: `evidence.example` is prose, not a field.",
        "  - https://egov-buryatia.ru/obr/index.php — «quoted»",
        "- **alongside: Е-услуги. Образование** — Е-услуги. Образование (admissions)."
        " Hosts: `es.zabedu.ru`. Since: 2020. Confidence: medium.",
        "- **previous: [БАРС](bars.md)** — Барс. Hosts: `школа.образование33.рф`,"
        " `xn--80atdl2c.xn--33-6kcadhwnl3cfdx.xn--p1ai`, `login.dnevnik.ru/login/esia/irkutsk`,"
        " `*.eljur.ru`. Confidence: low.",
        "- **alongside: [«Госуслуги Моя школа»](myschool-federal.md) as a front end** — app."
        " Hosts: `gosuslugi.ru/school`. Since: by 2025/26. Confidence: medium.",
        "- **alongside: [ФГИС «Моя школа»](myschool-federal.md)** — portal."
        " Hosts: `myschool.edu.ru`. Confidence: medium.",
        "- **previous: [БАРС](bars.md)** — the same platform again, earlier."
        " Hosts: `old.example.ru`. Confidence: high.",
        "- **Notes.** Hosts: `not.a.system` — notes are not systems.",
        "- **Checked:** confirmed.",
        "",
    ]
)


def test_a_full_stop_inside_since_or_a_label_does_not_move_the_hosts():
    """Anchored on «Hosts:», «Since:» and «Confidence:», never on the first full stop."""
    (region,) = generator.parse_survey(_BLOCK)

    assert region.name == "Республика Бурятия"
    assert region.mandatory
    primary, admissions = region.systems[0], region.systems[1]
    assert [host.display() for host in primary.hosts] == ["deti.obr03.ru", "sad06.ru:82"]
    assert primary.confidence == "high" and primary.page == "netschool"
    assert admissions.label == "Е-услуги. Образование" and admissions.page is None
    assert [host.display() for host in admissions.hosts] == ["es.zabedu.ru"]
    # Only the first line of a bullet is read: evidence and «Notes.» are prose.
    everything = [host.display() for system in region.systems for host in system.hosts]
    assert "evidence.example" not in everything and "not.a.system" not in everything


def test_a_host_keeps_its_port_and_path_and_an_idn_meets_its_punycode_twin():
    (region,) = generator.parse_survey(_BLOCK)
    bars = region.systems[2]

    assert [host.display() for host in bars.hosts] == [
        "школа.образование33.рф",
        "login.dnevnik.ru/login/esia/irkutsk",
        "*.eljur.ru",
    ]
    idn, path, pattern = bars.hosts
    assert idn.url() == "https://xn--80atdl2c.xn--33-6kcadhwnl3cfdx.xn--p1ai"
    assert path.url() == "https://login.dnevnik.ru/login/esia/irkutsk"
    assert pattern.pattern and pattern.url() is None

    sakhalin = generator.parse_host("netcity.admsakhalin.ru:11111")
    assert (sakhalin.ascii, sakhalin.port, sakhalin.path) == ("netcity.admsakhalin.ru", 11111, "")


def test_duplicates_in_the_survey_are_real_and_kept():
    (region,) = generator.parse_survey(_BLOCK)
    assert [system.role for system in region.systems if system.page == "bars"] == [
        "legacy",
        "legacy",
    ]

    regions = _regions()
    petersburg = [s["role"] for s in regions["saint-petersburg"]["systems"]
                  if s["platform"] == "petersburg"]
    assert petersburg == ["primary", "legacy"]
    bars = [s["role"] for s in regions["vologda"]["systems"] if s["platform"] == "bars"]
    assert bars == ["secondary", "legacy"]


def test_the_federal_page_is_split_by_host_not_by_label():
    """`myschool-federal.md` is ТОР on `gosuslugi.ru/school` and the portal on `myschool.edu.ru`."""
    platforms = generator._platforms(_overlay())
    (region,) = generator.parse_survey(_BLOCK)
    front_end, portal = region.systems[3], region.systems[4]

    assert generator._platform_of(front_end, platforms, {}, "x").key == "tor-myschool"
    assert front_end.front_end
    assert generator._platform_of(portal, platforms, {}, "x").key == "fgis-myschool"

    yanao = [(s["platform"], s["front_end"]) for s in _regions()["yanao"]["systems"]]
    assert ("tor-myschool", True) in yanao and ("fgis-myschool", False) in yanao
    assert _committed()["platforms"]["fgis-myschool"]["kind"] == "portal"


def test_a_label_with_no_page_must_be_in_the_overlay_word_for_word():
    platforms = generator._platforms(_overlay())
    (region,) = generator.parse_survey(_BLOCK.replace("Е-услуги. Образование**", "Е-услуги**"))

    with pytest.raises(generator.CatalogError, match="not in \\[unlinked\\]"):
        generator._platform_of(region.systems[1], platforms, dict(_overlay()["unlinked"]), "x")


def test_a_bullet_that_starts_like_a_system_but_does_not_parse_stops_the_build():
    front_end_line = next(line for line in _BLOCK.splitlines() if "as a front end" in line)
    broken = _BLOCK.replace(front_end_line, front_end_line.replace("medium.", "sure."))
    with pytest.raises(generator.CatalogError, match="Confidence"):
        generator.parse_survey(broken)

    no_dash = _BLOCK.replace("(bars.md)** — Барс.", "(bars.md)** Барс.")
    with pytest.raises(generator.CatalogError, match="cannot read"):
        generator.parse_survey(no_dash)


def test_the_summary_table_is_held_to_the_survey():
    regions_md = generator.REGIONS_MD.read_text(encoding="utf-8")
    table_md = generator.DIARIES_MD.read_text(encoding="utf-8")
    survey = generator.parse_survey(regions_md)
    generator.cross_check(survey, table_md)

    # Ленинградская's primary is «Сетевой город»; a table that said otherwise
    # would be one of the two documents lying about a region's diary.
    row = next(line for line in table_md.splitlines() if line.startswith("| Ленинградская область"))
    wrong = table_md.replace(row, row.replace("diaries/netschool.md", "diaries/eljur.md", 1))
    with pytest.raises(generator.CatalogError, match="Ленинградская"):
        generator.cross_check(survey, wrong)

    unbolded = table_md.replace("| **Москва** |", "| Москва |")
    with pytest.raises(generator.CatalogError, match="bold"):
        generator.cross_check(survey, unbolded)


def test_the_overlay_cannot_rename_an_allow_listed_region():
    """A renamed key would orphan every class and session stored under the old one."""
    overlay = tomllib.loads(generator.OVERLAY.read_text(encoding="utf-8"))
    for entry in overlay["region"]:
        if entry["key"] == "leningrad":
            entry["key"] = "lenobl"

    with pytest.raises(generator.CatalogError, match="leningrad"):
        generator.build(
            generator.REGIONS_MD.read_text(encoding="utf-8"),
            generator.DIARIES_MD.read_text(encoding="utf-8"),
            overlay,
        )


def test_a_dadata_spelling_two_regions_share_is_refused():
    overlay = tomllib.loads(generator.OVERLAY.read_text(encoding="utf-8"))
    for entry in overlay["region"]:
        if entry["key"] == "altai-krai":
            entry["dadata_names"].append("Респ. Алтай")

    with pytest.raises(generator.CatalogError, match="already places"):
        generator.build(
            generator.REGIONS_MD.read_text(encoding="utf-8"),
            generator.DIARIES_MD.read_text(encoding="utf-8"),
            overlay,
        )


# --------------------------------------------------------------------------
# The loader and the lexicon
# --------------------------------------------------------------------------


def test_the_loader_places_a_school_by_code_or_by_dadatas_spelling():
    assert catalog.get("leningrad").name_en == "Leningrad Oblast"
    assert catalog.get("nowhere") is None and catalog.get(None) is None
    assert catalog.by_code("47").key == "leningrad"
    assert catalog.by_code("78").key == "saint-petersburg"
    # A thirteen-digit KLADR id is the caller's to cut, and a guess is worse than a miss.
    assert catalog.by_code("4700000000000") is None
    assert catalog.by_code("4") is None and catalog.by_code(None) is None
    assert catalog.by_dadata_name("Респ Татарстан").key == "tatarstan"
    assert catalog.by_dadata_name("г. Москва").key == "moscow"
    assert catalog.by_dadata_name("Кемеровская область — Кузбасс").key == "kemerovo"
    assert catalog.by_dadata_name("РЕСП САХА (ЯКУТИЯ)").key == "yakutia"
    # «Алтай» is the republic and «Алтайский» the krai: exact, never partial.
    assert catalog.by_dadata_name("Алтай").key == "altai-republic"
    assert catalog.by_dadata_name("Алтайский край").key == "altai-krai"
    assert catalog.by_dadata_name("Алт") is None
    assert len(catalog.regions()) == 89


def test_normalise_name_drops_case_yo_and_punctuation():
    assert catalog.normalise_name("  Респ Саха /Якутия/ ") == "респ саха якутия"
    assert catalog.normalise_name("Королёв") == "королев"
    assert catalog.normalise_name("Ханты-Мансийский АО — Югра") == "ханты мансийский ао югра"


def test_the_directorys_school_words_are_the_phones():
    assert catalog.school_words() == tuple(_committed()["search"]["school_words"])
    assert {"школа", "сош", "гимназия", "лицей", "№"} <= set(catalog.school_words())


def test_the_search_lexicon_swaps_layouts_key_for_key():
    search = _committed()["search"]
    latin, cyrillic = search["latin_layout"], search["cyrillic_layout"]
    swap = dict(zip(latin, cyrillic, strict=True))

    assert "".join(swap[char] for char in "cfvfhf") == "самара"
    assert search["fold"]["ё"] == "е" and search["fold"]["—"] == " "
    assert {"республика", "область", "край", "округ", "г"} <= set(search["stop_words"])

    def transliterate(text: str) -> str:
        pairs = search["translit"]
        out, i = [], 0
        while i < len(text):
            source, target = next(pair for pair in pairs if text.startswith(pair[0], i))
            out.append(target)
            i += len(source)
        return "".join(out)

    # Best effort: a prefix of the name is all the search needs to land.
    assert transliterate("moskva") == "москва"
    assert transliterate("chelyabinsk") == "челябинск"
    assert "казань".startswith(transliterate("kazan"))
    # The English endings of the Russian ones, which letter by letter came out
    # as «чувашиа», «мансиыск» and «якуцк» and matched nothing.
    assert transliterate("chuvashia") == "чувашия"
    assert transliterate("bashkiriya") == "башкирия"
    assert transliterate("mansiysk") == "мансийск"
    assert transliterate("yakutsk") == "якутск"


def test_the_search_synonyms_are_english_words_for_the_names_words():
    """«St Petersburg» and «Moscow region» are how English writes two regions,
    and neither is a word of their names. «oblast» stays out of the stop words:
    dropping it would tie Moscow Oblast with Moscow on the query «moscow»."""
    search = _committed()["search"]
    assert search["synonyms"]["st"] == ["saint"]
    assert "oblast" in search["synonyms"]["region"]
    assert "oblast" not in search["stop_words"]
    names = {
        word for region in _committed()["regions"] for word in region["name_en"].lower().split()
    }
    for meant in search["synonyms"].values():
        assert set(meant) <= names, meant
